### PR TITLE
LPS-71052 

### PR DESCRIPTION
**Pull request by NolanChan**
In LPS-71039, `isSessionRedirectOnExpire` was corrected to return true if the user has portal property _session.timeout.redirect.on.expire_=`true`

However, we also need to fix `getSessionExpirationRedirectURL` to make sure that the correct session expiration redirect url is returned. At this moment, `ssoMap` is default injected with three SSO services that return `null` for their session expiration redirect url. I'm writing code to return the url set in _company.default.home.url_ if every sso does not have a url set.

### CODE REVIEW

**Comment by NolanChan** [comment]
I'm pretty sure I ran source formatter, so I'll try to re-open once more. if not then i pull down and source format again

**Comment by NolanChan** [comment]
ci:reopen

**Comment by NolanChan** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Source formatter was not run, please run it and resend.

**Pull request closed without merging**
