### PR TITLE
LPS-107677, LPS-108329

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-107677
**Issue:**
When import a site, Additional information button is displayed even though there are no changes between the site template and the site.

**Solution:**
Adding property configuration to allow user to set parameter `PortletDataHandlerKeys.LAYOUT_SET_PROTOTYPE_LINK_ENABLED`.

https://issues.liferay.com/browse/LPS-108329
**Issue:**
UI is broken due to FileNotFoundException. This is found when testing [LPS-107677](https://issues.liferay.com/browse/LPS-107677).

**Fix:**
Due to [LPS-107487](https://issues.liferay.com/browse/LPS-107487), it moved the file location of information_messages.jsp. So I changed the path to point to the new path.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/pull/2783

**Pull request closed without merging**
