### PR TITLE
Lps 127072

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-127072

Hello @SamZiemer ,

The issue occurs here due to to the call here: [DDMDisplayContext](https://github.com/liferay/liferay-portal/blob/fa6ecdb8ad0e059654aff51e1216a57a8ddd272a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/java/com/liferay/dynamic/data/mapping/web/internal/display/context/DDMDisplayContext.java#L998). When staging is enabled, but DDL is not staged, the groupId returned only has the staging group id. The intended behavior, as established, by [PTR-2198](https://issues.liferay.com/browse/PTR-2198) is to also include the liveGroupId.

The solution was implemented after an approval from the product team in the PTR.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @SamZiemer ,

Let me know if you see any issues with the PR.

Sincerely,
Brian Kim

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/vendeltoreki/liferay-portal/pull/167

Sorry for the delay in this.

**Pull request closed without merging**
