### PR TITLE
LPS-66077 Add Author and Modified Date fields when exporting DDLs

### PR DESCRIPTION
**Pull request by SpencerWoo**
LPS : https://issues.liferay.com/browse/LPS-66077
LPP : https://issues.liferay.com/browse/LPP-24713

I was told we typically don't handle feature request unless they can be framed as bugs, but I had already most of the fix.  I was told it's okay to try to submit it but I understand if we don't want features and this is closed.

This change populates Author and Modified Date fields from the DDL record / recordVersion.

### CODE REVIEW

**Comment by SamZiemer** [comment]
hi @SpencerWoo,

Some of these form test failures look as though they may be connected to your fix, can you please check into those? Also, please assign me the LPS in the review status with the pull request linked.

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SpencerWoo** [comment]
Hi @SamZiemer, Okay I'll look into the failing tests and the changes I've made.  The LPS is a feature request which doesn't have verified / in progress / in review which is why I wasn't sure if I should assign it as normal but okay I'll assign it to you.

**Comment by SamZiemer** [comment]
Hey, @SpencerWoo, I don't mind sending this through, but we will need to change the ticket a little so we can send it through the normal workflow.

Open a new Story LPS and link that to the original feature request LPS (LPS-66077) and we will use the story LPS for the normal workflow. When you resend the pull request, make sure you have changed the commit messages to the new LPS.

**Pull request closed without merging**
