### PR TITLE
LPS-109221 We don't need to update calendarResource for a default user.

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-109221

See ticket for issue description.

Solution is to ensure the calendarResource for a guest user is not updated.

The solution is consistent with the behavior introduced from https://github.com/liferay/liferay-portal/commit/151a7ca13f40dea2628523fefcbaec82e36fe465#diff-5ca8bc460cc7c74517a366a5622918f5 in which only a user name change warrants a calendarResource update. Guest users will never have their name values changed as it will always be "Guest".

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hello @SamZiemer ,

Please let me know if anything needs to be addressed in this PR. tests look good.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/rafaprax/liferay-portal/pull/1015

**Pull request closed without merging**
