### PR TITLE
LPS-71409

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @SamZiemer,

Original Ticket: [LPP-24542](https://issues.liferay.com/browse/LPP-24542)
LPS Ticket: [LPS-71409](https://issues.liferay.com/browse/LPS-71409)
SME Ticket: [LPP-24721](https://issues.liferay.com/browse/LPP-24721)

## Changes
The changes for this PR are pretty straightforward, an additional check is added to make sure that we only attempt to login if the request method is POST.

## NOTE
For this issue, the SME noted that this technically is not a bug:
> As the normal operation does not result login forms with GET method to be displayed for the end user I cannot consider this as a bug.
They can customize the corresponding action class to reject serving login requests with get method if they really need this behavior.

But, after talking with CS, we found that multiple customers have actually been reporting this issue as a security concern. I later discussed this with Minhchau and we decided to create this as a bug ticket and hope that the Security team will address this concern.

The SME also mentioned 
> Technically we could restrict to serve login requests only with POST method, though it would not prevent the browser to store whatever the user entered.

Although this issue may not be considered a bug from a technical standpoint, the current behavior of a successful user login could be considered a security concern from a customer's perspective.

----
Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@ericyanLr In LoginAction, if the method is not POST, should we simply return early or did you want to execute the redirect logic for a specific reason? I feel as if the login fails, no redirect should occur, but I could be misunderstanding what's happening.

**Comment by SamZiemer** [comment]
hey @ericyanLr, any update on Jonathan's question? I'll go ahead and close this PR out for now until you are able to determine the correct way.

**Comment by ericyanLr** [comment]
Hi @jonathanmccann @SamZiemer,

The redirect logic would redirect the user to the Login portlet's login page.
I figured that would be the best transition.

I think if we just returned early, it would result in a blank page.
I also considered redirecting to: `response.sendRedirect(themeDisplay.getPathMain())` before returning early as well.

Please let me know what you guys think would be better or if I should reach out to an SME for their input.

Thanks!

**Comment by SamZiemer** [comment]
hey @ericyanLr,

Can you test what happens with returning early? Also, what happens when a login fails using the current method?

**Comment by ericyanLr** [comment]
Hi @SamZiemer,

To test LoginAction, I will be using the following URL:
http://localhost:8080/c/portal/login?login=test&password=test

## Can you test what happens with returning early?
If we were to return early, for example:
```
if (!StringUtil.equalsIgnoreCase(method, HttpMethods.POST)) {
	return null;
}
```
The page would just return blank.

## Also, what happens when a login fails using the current method?
With the current commits, when a login fails, it will redirect the user to the Login portlet's login page:
http://localhost:8080/web/guest/home?p_p_id=com_liferay_login_web_portlet_LoginPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&saveLastPath=false&_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName=%2Flogin%2Flogin

**Comment by SamZiemer** [comment]
Thanks eric, I'll reopen this PR, can you re assign me the tickets?

**Comment by ericyanLr** [comment]
Hey Sam, tickets are now re-assigned to you.
Thanks!

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1274

**Pull request closed without merging**
