### PR TITLE
LPS-52107 - Children organizations do not inherit site membership from parent organizations

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Sam!
LPP: https://issues.liferay.com/browse/LPP-28259
LPS: https://issues.liferay.com/browse/LPS-52107

**Issue:**
The issue being reported by the client is that child organizations do not inherit site membership from parent organizations. 

**Summary of History:**
A previous LPP provides context for this fix. Specifically several decisions were made including:
- that the behavior of children organizations being added automatically is [intended](https://issues.liferay.com/browse/LPP-14323?focusedCommentId=548245&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-548245)
- that [users belonging to child orgs should be visible](https://issues.liferay.com/browse/LPP-14323?focusedCommentId=556942&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-556942) in Site Memberships -> Users upon being added through a parent org being added

A previous PR also outlined that the fix should work on preexisting organizations/sites, that it should account for a child organization being added to a parent organization after the membership is established, as well as automatic removal of all children if a parent is removed.

**The Fix:**
The fix involves checking if the children organizations of all site member organizations are members of the group on page load and adding them if they are not. Children organizations are also added when a parent organization is added and correspondingly removed when the parent is removed. This behavior only works for the 'highest tier' member in the relationship chain--so if Liferay Europe is added, then Liferay Spain is added as a member as well. However, if Liferay Global is added later, Liferay Europe is no longer considered independent and cannot be removed unless Liferay Global is removed. This means that inheritance is strictly enforced as mandatory and individual users and individual child organizations cannot be removed.

The fix itself uses a portal property to allow the user to determine the behavior they wish to have. It defaults to false which corresponds to how the portal works presently (inheritance does not occur). If set to true, inheritance will be enforced.

Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:retest

**Comment by wanderlast** [comment]
ci:reopen

**Comment by wanderlast** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Hi Lianne, I apologize for the delay in getting to this issue. Forwarded to https://github.com/pei-jung/liferay-portal/pull/253

**Pull request closed without merging**
