### PR TITLE
LPS-104445

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-104445

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@holatuwol the CSS below would be safer
```
.portlet-navigation {
	.portlet,
	.portlet-content,
	.portlet-content-container,
	.portlet-body,
	.portlet-body > div {
		display: flex;
		flex-direction: column;
	}
}
```
The selectors
```
.portlet-navigation {
	display: flex;

	div,
	section {
		display: flex;
	}
} 
```
is too generic and will bleed to all `div`'s and `section`'s inside `.portlet-navigation`. Also `display: flex` by itself causes the `portlet-topper` to appear next to the nav instead of on top of it.

**Comment by holatuwol** [comment]
@pat270 : I've applied the suggested change.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jbalsas/liferay-portal/pull/2037

**Pull request closed without merging**
