### PR TITLE
LPS-85410 Update workflowContext to save the approver's id

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-85410

Sending again as the test failures are not related to my changes.

Problem: The workflowContext is never updated with the approver's userId when the completeWorkflowTask() is called.

Solution: Pass in a workflowContext with the userId of the approver updated using same logic as [WorkflowHelper](https://github.com/joshuacords/liferay-portal/blob/83c8717c1c98b126a2717e88068cff732170e54d/modules/apps/portal-workflow/portal-workflow-rest/src/main/java/com/liferay/portal/workflow/rest/internal/helper/WorkflowHelper.java#L431-L439).
Considering there is no dependency from portal-workflow-task-web on portal-workflow-rest and the WorkflowHelper getWorkflowContext() method is protected, I believe it's better to mimic the logic rather than call the method.
I could also see the change being made at a lower level, such as in [DefaultTaskManagerImpl.doCompleteWorkflowTask()](https://github.com/joshuacords/liferay-portal/blob/ecd1a18ec043d0c50329d410ee2f8a8e7ba31bf5/modules/apps/portal-workflow/portal-workflow-kaleo-runtime-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/internal/DefaultTaskManagerImpl.java#L361-L362) but that logic is shared by other calls and the method signatures would need to add the userId, so I think this version of the fix is preferable.

### CODE REVIEW

**Comment by joshuacords** [comment]
I've reviewed the test failures in this comment here: https://github.com/SamZiemer/liferay-portal/pull/495#issuecomment-424810911

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
You can see that the original failures also happened on a blank fix here: https://github.com/joshuacords/liferay-portal/pull/24#issuecomment-424845977

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jeyvison/liferay-portal/pull/128

**Pull request closed without merging**
