### PR TITLE
LPS-137423 All related data should be deleted when a virtual instance is removed and DB Partition is enabled

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://issues.liferay.com/browse/LPS-137423>

__Notes:__
By setting the portal property `database.partition.migrate.enabled`, users can now choose between the following options when removing a virtual instance:

* Keep the database partition independent by copying control tables and migrating all relevant data from the default schema to the partition.
* Drop the database partition entirely.

For context, commit 1849ccc22986a8c43abdc8e5e5dc312b5ef0cfd8 fixes the bug described in [LPS-140833](https://issues.liferay.com/browse/LPS-140833). The issue is that, upon removal of the virtual instance, tables from the virtual instance database partition were being iterated, which would cause `DBPartitionUtil` to migrate tables that do not exist in the default schema.

Let me know if you have any questions/thoughts.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:stop

**Comment by kevhlee** [comment]
ci:stop

**Comment by SamZiemer** [comment]
After speaking with Kevin, we will separate the changes for LPS-137423 and LPS-140833, closing this PR.

**Comment by SamZiemer** [comment]
ci:stop

**Pull request closed without merging**
