### PR TITLE
LPS-99836 Reduce length to 1024 and send into review

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-99836
https://issues.liferay.com/browse/LPP-34555

LPS-99836 was recently committed here: https://github.com/brianchandotcom/liferay-portal/pull/77071

Because of the nature of the url length problem, it is difficult to reproduce and has not been reproduced in master. In our original testing on 7.1 bedf729391ee066dbb3c94cce2faf187665fcbf4  where the problem was reproducible. Setting the length to 2000, along with the other changes, was sufficient to solve the issue. However, when I went to apply the changes in master to a dxp-11 hotfix, the issue was still reproducible. After following the suggestion for setting the max length to 1024 [from StackOverflow](https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string/48230425#48230425), the issue was no longer reproducible on dxp-11.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @joshuacords, @SamZiemer, just copy-pasting my comment from JIRA:

> I don't think we should lower this anymore than 2000. This will start causing performance issues. We can agree on 2000 because it's a well tested limit that has proven to work reliably across servers and browsers. 
> 
> Seeing as it still seems to fail for you, could you try to figure out if this is a server configuration issue? If for some reason a specific application server has a lower limit and is not configurable, then we can revisit this. If it is configurable, we will need to make our limit configurable too so we can match user expectations, but we should not deteriorate everyone's experience out of the box.

/cc @izaera

**Comment by SamZiemer** [comment]
@joshuacords, based on the comments above, please resend after looking into this.

**Pull request closed without merging**
