### PR TITLE
LPS-70178 DDM structure validation error log improvement

### PR DESCRIPTION
**Pull request by NolanChan**
https://issues.liferay.com/browse/LPP-24025

Customer wanted a clearer log statement, so I'm including the field and structure name to help them pinpoint the issue

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Hey @NolanChan,

Can you put exact steps to reproduce on the LPS, this will be used by QA when testing the fix.

Thanks.

**Comment by NolanChan** [comment]
Hi @SamZiemer , I updated the LPS so it should be good to go for QA. Thanks for the reminder

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1186

**Comment by SamZiemer** [comment]
My mistake, this cannot be committed to master. @NolanChan, you will need to submit this fix to the journal sub repo rather than the master repo.

**Pull request closed without merging**
