### PR TITLE
LPS-74592 added handling for nested fields in template manager

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-74592

Hi Sam, this is Lianne Louie and this is my first pull request. Eric Yan made me type this.

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @wanderlast,

Thanks for sending the pull request. One of the things we do with the pull requests is run our CI tests on any submitted code. Please follow [this guide](https://in.liferay.com/web/global.engineering/blog/-/blogs/test-your-pull-requests) and set up pull request testing on your repo. The main part you need to do is publicizing your membership to the Liferay organization which can be found [here](https://help.github.com/articles/publicizing-or-hiding-organization-membership/). However, if you want to do the rest, that will allow you to send pull requests to yourself and the CI tests will run automatically to ensure they pass before sending them up the review chain. This is not required, however, but can be done if you are not sure if the tests will pass, or are writing your own tests.

Another thing to keep in mind is the Liferay [development style ](https://web.liferay.com/community/wiki/-/wiki/Main/Development+Style). A lot of the things can be caught by the source formatter, so be sure to run that before you send any pull requests. If you have questions on how to run that Eric or Greg should be able to answer any questions. I have not looked at the code you sent yet, so I am not sure if there are any issues with it or not, just giving you a heads up.

Once you have that setup, let me know and I will get the tests running.

Let me know if you have any questions.
Sam

**Comment by wanderlast** [comment]
@SamZiemer, thanks for all of the info! It's super helpful.

I set up everything, so hopefully it's working and everything is showing properly. Eric fortunately had me run source formatter already, so the code should be ok on that front.

What the code addresses is that the names of nested fields weren't showing in the template manager and, when displayed, weren't being referenced correctly. The correct reference to a nested field "Child" would be "Parent.Child" or "Grandparent.Parent.Child" (so on and so forth), but the field was only referring to "Child". Therefore, the altered code creates a map of <child,parent> pairs (since the method to find children/nested fields only finds those one level in) and then creates a stack so that the full line of nesting can be traced back and the proper reference is written.

-- Lianne

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Thanks @wanderlast,

I'll let the CI tests run and review the code changes.

**Comment by SamZiemer** [comment]
@wanderlast, it looks like I'll need to have you send this pull request to the [dynamic-data-mapping subrepo](https://github.com/liferay/com-liferay-dynamic-data-mapping). Dynamic data mapping, along with Journal, and a few other modules are split off into their own separate repositories and the head of those repositories is pulled by the main liferay-portal/master when compiling those modules. This, unfortunately, makes things a little more complicated for us when we send pull requests.

If you need help setting up the sub-repo, let me, or anyone on the team, know, since I think Eric is out of the office.

**Comment by wanderlast** [comment]
@SamZiemer Got it! I'll look into it, thanks!

**Pull request closed without merging**
