### PR TITLE
LPS-82856

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-30605
https://issues.liferay.com/browse/LPS-82856

Scheduled publications when using remote live staging will fail if a page that is scheduled to be published is deleted prior to the publication.

This is because the settings map that indicates which layouts to publish (configured at the time of scheduling the publication) is reused when the publication is executed to determine which layouts to publish. Any number of these layouts could have been deleted since that time, but it does not handle this case gracefully.

I think the correct way to handle this is to simply add a little more error checking/handling. Let me know if there are any other problems with this I did not foresee, though. Thanks!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Closing this for now due to the freeze for master.

**Comment by SamZiemer** [comment]
Hi @Alec-Shay This fix looks good to be moved forward, once the code freeze has been lifted please send this forward to Eudaldo Alonso, github name of ealonso.

**Comment by Alec-Shay** [comment]
Sounds good to me. Thanks @SamZiemer!

**Comment by matethurzo** [comment]
hey again, this is 100% staging code, I should review this. this has been classified as we want to fix for 7.1 so please forward it to me

**Comment by Alec-Shay** [comment]
Sent to: https://github.com/matethurzo/liferay-portal/pull/2162

**Pull request closed without merging**
