### PR TITLE
LPS-129336

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-129336

Hello @SamZiemer ,

Straightforward issue here. We are updating xstream to 1.4.16 due to the security issues reported in LPS-129336.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hello @SamZiemer ,

I am not sure how to address the SF failure here. Please let me know what I should be doing.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/liferay-appsec/liferay-portal/pull/308

**Pull request closed without merging**
