### PR TITLE
LPS-86440

### PR DESCRIPTION
**Pull request by jonathanmccann**
### Explanation of changes in https://github.com/SamZiemer/liferay-portal/commit/368005853c1f0da830be65f7674435a9f71b3ddb

Since these are unit tests the portal does not need to be running like when performing integration tests. Due to that we need to make sure the classes we are utilizing are initialized properly. In https://github.com/SamZiemer/liferay-portal/commit/550bdcac5185ec330433d98e33f9bf240354e28e#diff-1fbfbd36b8c7387a347b33c5ad2c1c19R333 a dependency on `ParamUtil` was introduced. `ParamUtil` contains a [static block](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/ParamUtil.java#L2507-L2526) that relies on `PropsUtil`. When the portal is running normally, `PropsUtil` will have it's `_props` set correctly but since this is a unit test this does not occur.

In this case what we need to do is manually initialize `PropsUtil` with a value to avoid the NullPointerException.

This was discovered by the cause of the initial exception thrown for the first test run:

```
Caused by:
        java.lang.NullPointerException
            at com.liferay.portal.kernel.util.PropsUtil.get(PropsUtil.java:31)
            at com.liferay.portal.kernel.util.ParamUtil.<clinit>(ParamUtil.java:2508)
            ... 65 more
```

### Explanation of changes in https://github.com/SamZiemer/liferay-portal/commit/93f0f6a1291c83f177fdba2c21ac50bc433f0a4a

For this test, the following error was logged:

```
java.lang.NullPointerException
        at com.liferay.dynamic.data.mapping.storage.DDMFormFieldValue.getDDMFormField(DDMFormFieldValue.java:71)
```

The call to `ddmFormFieldValue.getDDMFormField()` in https://github.com/SamZiemer/liferay-portal/commit/550bdcac5185ec330433d98e33f9bf240354e28e#diff-1fbfbd36b8c7387a347b33c5ad2c1c19R299 causes this exception to be raised since the `_ddmFormValues` have not been initialized.

If you guys have any questions please let me know.

/cc @diana-lin @joshuacords

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by diana-lin** [comment]
Thank you for the help and the thorough explanations @jonathanmccann.  Those changes make sense.

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:retest:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/rafaprax/liferay-portal/pull/897

**Pull request closed without merging**
