### PR TITLE
LPS-68710

### PR DESCRIPTION
**Pull request by SGM3**
Corrected issue with child redirect URL not having the correct redirected URL and the issue with redirect parameter growing in length upon page update until the URL string is invalid.

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @SGM3,

Please assign the LPS to me in the review status.

**Comment by SGM3** [comment]
Hi @SamZiemer ,
So will I need to reopen/open a new PR this once master updates that version number?

**Comment by SamZiemer** [comment]
No, this has been happening a lot lately, I will check it out and probably reopen this one.

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1139

**Pull request closed without merging**
