### PR TITLE
[TECHNICAL SUPPORT] LPS-72877

### PR DESCRIPTION
**Pull request by thomasstew**
Relevant Ticket:
[LPS-72877](https://issues.liferay.com/browse/LPS-72877)

The bug presented in this ticket is caused by a p_p_id being present when getting a RequestDispatcher.

This fix corrects the logic in the isAllPublicRenderParameters method so when it is called in the populateParams method, a p_p_id is not added. 

The logic for isAllPublicRenderParameters checks to see if all router params are also present in the public render params. However, if the public render params are empty and there are still router params, this method would return true. This fix adds a check to return false if public render params is empty, but there are still router params.

### CODE REVIEW

**Comment by thomasstew** [comment]
ci:reopen

**Comment by thomasstew** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1333

**Comment by SamZiemer** [comment]
@thomasstew 

For future pull requests, please see the [LPS ticket SOP and workflow](https://in.liferay.com/web/support/wiki/-/wiki/Main+Global/TS+LPS+SOPs) here and follow the appropriate workflow. If this issue is related to an LPP, please also see the [LPP ticket SOP and workflow](https://in.liferay.com/web/support/wiki/-/wiki/Main+Global/LPP+Patch+Workflow). Please read both of these workflows to ensure you are following the proper SOP for these tickets.

When submitting for review, you need to ensure all tickets are assigned to the proper status and to the proper person. In addition, you need to make sure all tickets are linked together correctly. This helps everyone in the review chain track what is happening more accurately.

One last note, when you commit the commit message must ALWAYS contain the LPS number first before any message. I, unfortunately, did not catch this before I submitted the pull request further, but it was caught by Jonathan Mccann.

From now on, when the ticket SOP is not followed correctly I will be closing the pull requests and handing everything back to you.

**Comment by thomasstew** [comment]
Hi @SamZiemer,

Sorry about that! I will be sure to double-check the SOP going forward.

**Pull request closed without merging**
