### PR TITLE
LPS-97660

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-97660

Hello @SamZiemer ,

After the introduction of LPS-78738,  use of "_"  has been replaced with "-" in the locale of the URLs as part of SEO improvement. However, this change was not reflected in how we generate the URLs in the [head element](https://github.com/liferay/liferay-portal/blob/5bad9b73b6e3431b71543e8d5ce1d46afe8347b2/portal-web/docroot/html/common/themes/top_head.jsp#L34-L53). As a result, our SEO performance is poor.

The fix is to ensure we apply the precedent set in LPS-78738 to our creation of [alternateURLs](https://github.com/liferay/liferay-portal/blob/5bad9b73b6e3431b71543e8d5ce1d46afe8347b2/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L8302-L8339).

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hey @brianikim,

This may affect more than just the performance of SEO. Is there another area we can replace the - characters? If not, please look at everything that touches this method to make sure it does not break functionality for those use cases.

**Comment by brianikim** [comment]
Hey @SamZiemer ,

Great point. I am currently assessing whether the proposed change will potentially break functionality for other use cases not related to SEO.

**Comment by holatuwol** [comment]
@SamZiemer, @brianikim : It looks like this function is intended to build URLs that will be recognized by I18nServlet, and due to https://github.com/liferay/liferay-portal/commit/92456c0698fe6ffade0c8ddfd030abc2a502c550, the underscore version will always send a 301-redirect to the dash version.

With that being said, it seems strange that we're doing something that looks different from what I18nServlet does (see the previous linked commit's `sendRedirect` method, which uses [Locale.toLanguageTag](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#toLanguageTag())), so we should double-check the new logic.

**Comment by brianikim** [comment]
Hello @SamZiemer ,

I am currently discussing with Minhchau on best practices on which method call to use for displaying the locale.

As for your concern, I was able to determine that making the change at the root is necessary as the methods that utilize _buildI18NPath are all user-facing and we want users to know the correct URL patterns to use. The change will not break functionality for the methods.

**Comment by SamZiemer** [comment]
Thanks for checking on that Brian!

**Comment by brianikim** [comment]
Hey @SamZiemer ,

I reopened the PR as changes were determined to be not necessary.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/adolfopa/liferay-portal/pull/1046

**Pull request closed without merging**
