### PR TITLE
J cords lps 72770 2

### PR DESCRIPTION
**Pull request by joshuacords**
Added the LPS-72118 Revert as suggested by @dacousair and tested for the problems in LPS-72118 and LPS-72770. Everything is still fixed as expected.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1332

**Pull request closed without merging**
