### PR TITLE
LPS-74100

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @SamZiemer,

This was kind of a nasty one. I ended up having to use reflection to update the resourceBlockIds of the persistedModels - I couldn't figure out any other way to do it since we don't have any of their primary keys. If you have any better ideas, please let me know.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by mbowerman** [comment]
Shouldn't be related as DLFolder doesn't use ResourceBlock...

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/mdelapenya/liferay-portal/pull/549

**Pull request closed without merging**
