### PR TITLE
LPS-95136 Web Content content out of range in the portlet

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-95136

Previous pr: gregory-bretall#191
New pr because gregory-bretall#191 (comment)

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/pull/2370

**Pull request closed without merging**
