### PR TITLE
LPS-166637 - Alerts for required fields with matching styles

### PR DESCRIPTION
**Pull request by Gabriel422-hue**
Hey Sam!

Fixed style, as per design indications.

Related Issue: https://issues.liferay.com/browse/LPS-166637

### CODE REVIEW

**Comment by Gabriel422-hue** [comment]
ci: test: sf

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Comment by Gabriel422-hue** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hi @Gabriel422-hue, Great job on this ticket! I believe this solves the issue and I will forward it on.

**Comment by SamZiemer** [comment]
Pull Request forwarded to https://github.com/liferay-lima/liferay-portal/pull/3749

**Pull request closed without merging**
