### PR TITLE
LPS-71050

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-24514
https://issues.liferay.com/browse/LPS-71050

For this issue, we found that there are some options for "import strategies" when importing data (under the "Update Data" section) through the staging framework which are often unimplemented, but still have the options present. Specifically for this pull we are more concerned with "Mirror with overwriting", but "Copy as New" may deserve some attention as well. This is true both in DXP and 6.2.

From the help message shown, as well as the original documentation here, it seems that the "Mirror with overwriting" import strategy was initially only intended for documents (which are the only component implementing it currently), but the option for it is included for every component regardless of whether it does anything. Thus, as it is now, this option does nothing at all for many components, and is very misleading for users (this is similar for the "Copy as New" strategy, although there already is a change like this for that, and also most components implement it).

From our discussion, we concluded that it ultimately is up to the owners of the individual components whether these strategies should be implemented at all; in some cases it may make sense to give this as an option, or sometimes it may not. So the main change here is to add support for components to easily disable this option, so that the components may individually decide whether to implement or disable the option (it should definitely be either one or the other for each though).

Also please note that while I updated import_portlet_resources.jsp, import_layouts_resources.jsp is fine as is, because it encompasses many components, so even if it only works for one component, it should still have the option (although it may be nice to be able to fine-tune it).

Also, I added a commit that hides the entire "Update Data" section if none of the options can be changed (Alec-Shay@aabb32f), just because I thought it was more intuitive to do so. However, you could also argue that this makes too much inconsistency between the different types of content, so I'm not sure if this is the right way to go. I just threw this in, but feel free to drop the commit if it doesn't seem like a good change.

We may need to create sub-tasks in the future so that we can get more component owners to make this decision for affected types of content. Or perhaps we should disable it for everything where it's not currently implemented? I wasn't sure if this was too aggressive of a change for now, so I just targeted the use case on our customer issue. Our use case is more concerned with Web Content, so I will also be sending a pull for the journal repository together with this.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
/cc @moltam89

Sent related pull to com-liferay-journal repository: https://github.com/SamZiemer/com-liferay-journal/pull/6

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Hey @Alec-Shay,

Can you add steps to the lps to reproduce? I'll use the steps from the lpp, but QA will need some on the lps.

**Comment by Alec-Shay** [comment]
@SamZiemer I guess steps just for the journal change then? I guess that would make sense, and I can do that. Initially I didn't think any of it would be testable for QA because I was just planning on doing the API change.

**Comment by SamZiemer** [comment]
Were you able to test with the steps on the lpp?

**Comment by Alec-Shay** [comment]
We're not sure we'll be able to fix that use case in particular. The expected result on the LPP would be a new feature.

**Comment by SamZiemer** [comment]
ahh ok. we can pass it up as it for now with your notes

**Comment by Alec-Shay** [comment]
Ah, okay. Thanks.

**Comment by moltam89** [comment]
Hi guys,

the logic seems good to me, though I'm not sure that we should hide the update data section.
I think it can be confusing for the users, though I agree that showing a section without real options can be confusing as well.
For now, I wouldn't change the UI, maybe we can handle the UI related changes in another ticket, consulting with the product management for the best user experience.

Cheers,
Tamás

**Comment by Alec-Shay** [comment]
I'm not sure about it either, I just threw in the commit as sort of a suggestion. I guess we can handle it on another ticket though (I wonder what the best way to get in touch with UX would be for it?)

**Comment by moltam89** [comment]
I think the best way would be to open a Product Team Requests.
I could imagine a solution like the "Update Data" section is grey, or something similar, if there are no options, but I tend to think it's more like a design issue.
I guess it couldn't hurt either to raise Máté's attention on this matter once this pull request reaches him.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1247

**Pull request closed without merging**
