### PR TITLE
[TS] LPS-93908

### PR DESCRIPTION
**Pull request by brianikim**
Hello @SamZiemer ,

Notes from @matthewchan123:

> https://issues.liferay.com/browse/LPS-93908
> 
> Issue:
> Text in Account Settings > Apps leads one to believe the third party apps are connected to Liferay, when it is actually the other way around.
> 
> Fix:
> Reword language key + value and add this change to available Language.properties files.

### CODE REVIEW

**Comment by brianikim** [comment]
ci test result here: https://github.com/brianikim/liferay-portal/pull/20#issuecomment-482700360

**Comment by SamZiemer** [comment]
Hi @brianikim, @matthewchan123 

The language key Revoke was not changed at all, except for a line ending, so the translations should not have been updated at all either. Please rework the initial commit so that the line ending of the file is not changed at all then run the build lang.

**Comment by matthewchan123** [comment]
Hi @SamZiemer,

I looked into this issue of circumventing git tracking for changes to the Revoke line. However, it seems that with git it is likely not possible to leave parts of a line unchanged, as git keeps track of changes cohesively by line number. A newline character is added to each revoke language key, so unfortunately the whole line will need to appear modified in this case.

**Comment by SamZiemer** [comment]
@matthewchan123 you need to manually edit the file, not with git, but with sublime or intellij to add or remove a new line(whichever is needed in this case). You can check with gitk or git log to see if that removes git tracking the change.

**Comment by matthewchan123** [comment]
okay, @SamZiemer.  I made the new line addition using sublime text, and here is what I saw before and after the change:

Screenshot from 2019-04-17 13-25-29

Screenshot from 2019-04-17 13-25-58

**Comment by SamZiemer** [comment]
@matthewchan123 Go with whichever option does not have a change in the git diff for that line.

**Comment by matthewchan123** [comment]
@SamZiemer Sorry for the misunderstanding, these images were meant to show that git always tracks the entire line after adding a single newline character. Using Sublime editor does not remove git tracking here of "revoke=Revoke", neither has trying intelliJ or Vim.

**Comment by SamZiemer** [comment]
I'll be in tomorrow to help you out. First, though, did you try running the source-formatter after making your commit? I should usually catch these things.

**Comment by matthewchan123** [comment]
No changes came out of running source-formatter.

**Pull request closed without merging**
