### PR TITLE
LPS-139166 Add integration tests

### PR DESCRIPTION
**Pull request by kevhlee**
**Tickets:**
<https://issues.liferay.com/browse/LPS-139166>
<https://issues.liferay.com/browse/LPS-138029>

**Notes:**
Pull request originally sent to @achaparro (https://github.com/achaparro/liferay-portal/pull/1019). In general, the integration tests do the following:

- Check if tables are sorted by initial number of rows (or by name if initial rows are equal).
- Verify that tables that are empty before and after upgrade are excluded.
- Verify that upgrade report catches changes in number of rows.

Let me know if anything should be changed.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
ci:forward

**Pull request closed without merging**
