### PR TITLE
LPS-68349

### PR DESCRIPTION
**Pull request by NolanChan**
Documents and Media Portlet now defaults to Page 1 when 'items per page' is changed

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @NolanChan,

If this issue is a unique issue to 6.2.x you need to specify why it does not occur in master. If there is a fix in master that has already been made, that should be backported rather than creating a new, unique fix for 6.2.x.

Please update this pull request accordingly.

Thanks,
Sam

**Comment by SamZiemer** [comment]
Hi @NolanChan,

I'm going to close this pull request for now, please answer the previous questions and re open this pull if it is applicable.

**Comment by NolanChan** [comment]
Hi Sam, in regards to the question:

In Master, Liferay overhauled the javascript for the pagination to not send the "current page" URL argument when the "Items per page" is changed. This causes the searchContainer to fall back on its default "current page" when the page refreshes, which is page 1. Since the javascript is completely changed, I'll be needing to make a unique fix to 6.2.x

**Comment by SamZiemer** [comment]
As mentioned in my message to you, this needs to be sent against the liferay-portal-ee:ee-6.2.x branch.

**Pull request closed without merging**
