### PR TITLE
LPS-68379 Username does not overlap with discussion controls in Page Comments

### PR DESCRIPTION
**Pull request by NolanChan**

### CODE REVIEW

**Comment by ChrisKian** [comment]
The code changes have nothing to do with pmd, they are simple front-end tweaks

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by NolanChan** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1074

**Pull request closed without merging**
