### PR TITLE
LPS-104356 Image URL's groupId used in Page Fragments does not adjust upon Import

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-104356

**Issue**: 
Importing a Page Fragment that is associated with an image results in the Page Fragment image being broken. This is because the groupId associated with the image link is not updated to the new site's groupId. The original groupId is retained and its visibility would depend if there is an existing groupId in this bundle's instance. 

**Solution**: 
`_fragmentEntryLinkExportImportContentProcessor.replaceExportContentReferences()` makes the link updates possible when the contents are imported because it appends `dlReference`, which `replaceImportContentReferences()` searches for to then replace with the updated link.

Using `replaceExportContentReferences()` when exporting content, updates the image links to have references. Originally, the exported links did not hold references so when importing the content, the links could not be updated. The addition of `replaceExportContentReferences()` allows finding link patterns and appending `dlReference`, which would be required because `replaceImportDLReferences()` will replace the `dlReference`. However if no `dlReference` exists within the content, the links will not be updated.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/compare/master...SamZiemer:LPS-104356

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/pull/2621

**Pull request closed without merging**
