### PR TITLE
LPS-71727

### PR DESCRIPTION
**Pull request by NolanChan**
Improved Logging For LDAP Imports that Duplicate GroupFriendlyUrl's

https://issues.liferay.com/browse/LPS-71727
https://issues.liferay.com/browse/LPP-24995

Error message now reads:

`importing user CN=justin b: null:null:{samaccountname=sAMAccountName: justin} duplicates a group friendly url
com.liferay.portal.kernel.exception.GroupFriendlyURLException`

### CODE REVIEW

**Comment by NolanChan** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1285

**Pull request closed without merging**
