### PR TITLE
LPS-73629

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @SamZiemer,
This pr mainly focuses on handling nulls when retrieving a field.

**Note: Additional Change when adding onblur validation listener(s)**
While working on adding null checks for the method that adds onblur validation listeners, I noticed that it only retrieved one field per key:
``` var field = A.one('[name="<portlet:namespace />' + key + '"]');```

This meant that if a **radio type** field was used with multiple options, only **one radio option** would have a registered listener.

So, I added an additional change to retrieve all the fields associated with the key, to account for the radio type:
```var fields = A.all('[name="<portlet:namespace />' + key + '"]');```

This allows us to handle the null check by utilizing the returned [NodeList:](http://alloyui.com/api/classes/NodeList.html#method_each)
```fields.each(addOnBlurFieldValidation);```

**Original Tickets:**
[LPS-73629](https://issues.liferay.com/browse/LPS-73629)
[LPP-25030](https://issues.liferay.com/browse/LPP-25030)

----
Also, I did not assign you to the the original [LPP-25030](https://issues.liferay.com/browse/LPP-25030), as it is currently assigned to Michael for reviewing a backport, which is also needed to resolve the ticket.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by ericyanLr** [comment]
As discussed, I'll be updating the pr. Will leave another update after I push the changes.

**Comment by ericyanLr** [comment]
Hi @SamZiemer,
I have added an additional commit to account for the radio type during validation.

Please let me know if you have any questions.
Thanks!

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1378

**Pull request closed without merging**
