### PR TITLE
LPS-68710 Corrected redirect URL for child KB articles

### PR DESCRIPTION
**Pull request by SGM3**
Corrected redirect URL for child KB articles. Should now render the correct success message when submitting suggestions.

### CODE REVIEW

**Comment by SGM3** [comment]
ci:retest

**Comment by SGM3** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Hi @SGM3,

This pull request cannot be re opened due to the branch it is based on being force updated after it was initially closed. So a new pull request will need to be created for this issue.

However there is still some things on the LPS that need to be addressed. With your fix, the success message appears correctly, however the page still redirects incorrectly.

Once a suggestion is made, the page should simply be updated with the suggestion added, and not be redirected back to the KB article list.

Let me know if you have any questions.

Thanks,
Sam

**Pull request closed without merging**
