### PR TITLE
LPS-127135

### PR DESCRIPTION
**Pull request by kevhlee**
**Ticket:**
<https://issues.liferay.com/browse/LPS-127135>

**Notes:**
Users are not able to create a new organization via the Headless Admin API because `_getDTOConverterContext()` expects an organization ID, not the organization as an object string. Doing this causes an exception, resulting in a 404 error. This fix was originally developed by @javierdearcos from the Liferay Headless Team. I am simply pushing his changes to `master`.

cc: @javierdearcos

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Running CI tests again as the failed tests don't look directly relevant.

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:reevaluate:1122004_4179

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/drewbrokke/liferay-portal/pull/1290

**Pull request closed without merging**
