### PR TITLE
LPS-89922

### PR DESCRIPTION
**Pull request by brianikim**
Hello @SamZiemer ,

https://issues.liferay.com/browse/LPS-89922

The issue here is that when you attempt to add document types past the maximum number of types allowed in the creation menu in Documents and Media, the remaining document types are suppose to be displayed by clicking the "More" button that appears. However, clicking the button does nothing because we completely lack the implementation for Documents and Media.

The solution is to implement the feature.

Please let me know if you have any questions regarding the implementations.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:SF

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @SamZiemer ,

Surprisingly, even with all these failures, none of them look related to the fixes that I have introduced.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
Hello @SamZiemer ,

I talked with Fortunato regarding the two failures for the managementToolbar and I believe those two might actually be related to the fixes that I have introduced as I do use the managementToolbar to implement front-end for search and filtering.

I would like to re-run CI:TEST one more time to confirm. I will close and resend the PR depending on the results of that test.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/adolfopa/liferay-portal/pull/824

**Pull request closed without merging**
