### PR TITLE
J cords lps 74454

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-74454
https://issues.liferay.com/browse/LPP-26631

Deleting an instance or multiple instances (with Following option) of a recurring calendar booking will now notify participants.
The children of the calendar event were found through different logic than what deletes the events because changing the deleteCalendarBooking method [here](https://github.com/liferay/liferay-portal/blob/3244e1d8430abffb737ad6aeeac50749cbce8faf/modules/apps/forms-and-workflow/calendar/calendar-service/src/main/java/com/liferay/calendar/service/impl/CalendarBookingLocalServiceImpl.java#L516) and elsewhere would create cascade of changes to the portlet.
Originally I found that the best pattern to follow would be: 
-Users aren't notified if the deleted event is in the past.
-User is notified with Deleted template if 1 occurrence is deleted
-User is notified with Updated template if multiple occurrences are deleted
However, our framework doesn't have the supporting methods necessary to easily implement this. In particular calendarBooking.getStartTime() is not updated when the first event in a recurring series is deleted. As such, I just to the Delete Notification Template when a user deletes 1 or more instances of a Calendar Booking. This breaks with the implementation a little, but it doesn't seem worth the effort to follow it perfectly in this case.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:reopen
ci:retest

**Comment by joshuacords** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1407

**Pull request closed without merging**
