### PR TITLE
LPS-70514

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
Ugh, I modified one build.gradle file in the Journal subrepo when I used Minhchau's fixdeps script. I worry that if I remove that change, it will cause the tests to fail. What should I do?

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
Hey @SamZiemer, I removed the change to journal-service/build.gradle, and force-pushed the branch. I've sent you the change to journal-service/build.gradle separately at https://github.com/SamZiemer/com-liferay-journal/pull/5.

**Comment by mbowerman** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1210

**Pull request closed without merging**
