### PR TITLE
LPS-72648

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-25555
https://issues.liferay.com/browse/LPS-72648

When viewing a Dynamic Data List in "spreadsheet view," fields that are repeatable will either not display correctly, or cause the page to fail to load with a stack trace in the console.

This is because DDLImpl's [getRecordJSONObject() method](https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-service/src/main/java/com/liferay/dynamic/data/lists/internal/util/DDLImpl.java#L80) does not take repeatable fields into account; repeatable fields' values are retrieved as an array of field values, but treated as though they are a single Object (typically a String). A single JSONObject is expected to hold the value for the JSONObject using the field name as an identifier.

I thought of a few ways this could be solved for the "spreadsheet view" case in particular (like using something other than DDLImpl to retrieve the DDLRecord values), but as of now I think this is the correct way to do it, since the code in this method appears to be incorrect regardless; I essentially just fit all the values into a list of values where appropriate, so they could still be used within a single JSONObject like this method presupposes. This did mean a lot of the code had to be rewritten to allow for it to be done in a loop, however.

Please let me know of any questions, concerns, or improvements that can be made. Thanks!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Hey @SamZiemer,

I feel like something like this is the right way to go for this issue, but as you can see from the commit, I ended up take a pretty big method and rewrite most of it. It seems to work good to me for all the different data types, but I wonder if the implementation looks right. What do you think?

**Comment by SamZiemer** [comment]
hey @Alec-Shay, I'm taking a look at this now.

**Comment by Alec-Shay** [comment]
Thanks, Sam!

**Comment by SamZiemer** [comment]
Hey @Alec-Shay 

This fix looks good to me. Since we do need to handle the array values I'm not sure we could handle it another way.

Forwarded to https://github.com/marcellustavares/liferay-portal/pull/1872

**Comment by Alec-Shay** [comment]
@SamZiemer Okay, cool. Just wanted a good second opinion.

Thanks!

**Pull request closed without merging**
