### PR TITLE
J cords lps 73348 2

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPP-25804
https://issues.liferay.com/browse/LPS-73348

Because Resource Block Permissions function differently than Resource Permissions in that their group scope data is lossy, this PR is providing improved warnings to the User before their change overwrites Permissions set in the Group Scope. (Changing the functionality is too big of a task, as discussed here: https://issues.liferay.com/browse/LPP-25978)

Additionally, this PR removes an issue where setting a permission for a ResourceBlock resource at the company level will no longer overwrite all permissions on that resource, instead it will only overwrite the permission changed.

Note: Not all language keys have been generated.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Hi @joshuacords,

These test failures look like they may be related to your changes, can you take a look, thanks.

**Comment by joshuacords** [comment]
@SamZiemer I believe these tests were failing because empty arrays were not properly being handled. I corrected the javascript code which should also fix the test failure.

**Comment by joshuacords** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Thanks, @joshuacords, I'll review this once the tests have completed again.

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/JorgeFerrer/liferay-portal/pull/830

**Pull request closed without merging**
