### PR TITLE
LPS-127800 Use instance id when editing web content display

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-127800

The issue here was that multiple success messages were being displayed when editing a web content display. The number of display messages were dependent on how many web content displays were added to a page.
To fix the issue, the instance id of the web content display is passed into the request.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevent

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
forwarded to https://github.com/liferay-echo/liferay-portal/pull/3810

**Pull request closed without merging**
