### PR TITLE
LPS-65130

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @mbowerman 

Can you please run the source formatter, and update the commit message to be more in line with the actionable dynamic query usage, rather than using an sql statement.

**Comment by SamZiemer** [comment]
@mbowerman 

My apologies, I did not mean to close out this pull request, this can be done as an update.

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Thank Michael, I have forwarded the review to https://github.com/dustinryerson/liferay-portal/pull/51

**Comment by SamZiemer** [comment]
ci:retest

**Pull request closed without merging**
