### PR TITLE
LPS-77842 (update)

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant ticket:

https://issues.liferay.com/browse/LPS-77842

As per [the comment on our previous pull request](https://github.com/liferay/liferay-portal-ee/pull/6367#issuecomment-383540959) for backporting LPS-77842, the fix should be for the 7.0.6 UpgradeProcess for us to be able to backport it to 7.0.x. This change simply refactors the changes from LPS-77842 for 7.0.6 instead of 7.1.x, because we need to be able to backport it.

Please let me know if there are any problems moving forward with this. Thanks!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by Alec-Shay** [comment]
@SamZiemer I did the refactoring manually, although it should be noted that the changes for `RepositoryTable` were originally added with an automated command (`ant build-upgrade-table` with a parameter for the directory).

I reran the command again and no further changes were needed, so I figured it made more sense than deleting it all just to regenerate it again. If you think it needs to be removed an regenerated again though, I can always resend it.

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/achaparro/liferay-portal/pull/190

**Pull request closed without merging**
