### PR TITLE
LPS-139161 DB Partitioning should use the client session charset or the Db default one

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://issues.liferay.com/browse/LPS-139161>

__Notes:__
Instead of using `utf8` by default for the new partition schemas, we should use the character set encoding specified for the database session, which can be retrieved by reading the value set for the session variable `character_set_client`. Note that the `character_set_client` session variable is set when supplying the value for `characterEncoding` in the JDBC string. See following link for more information:

* <https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_character_set_client>
* <https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-session.html>

Let me know if you have any questions/thoughts.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
Hi @SamZiemer,

I want to double-check the MySQL documentation to make sure we're reading the system variable that's appropriate for LPS ticket's use case. I'm going to close this PR for now.

**Comment by kevhlee** [comment]
Based on the documentation, I think using the `character_set_client` variable is appropriate.

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Thanks for this fix @kevhlee I think this looks like a good approach as we will be using the same character set the user is setting in the initial jdbc settings.

**Comment by SamZiemer** [comment]
ci:forward

**Pull request closed without merging**
