### PR TITLE
LPS-126485 Allow only alphanumeric characters.

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-126485

Straight-forward issue. We should only allow alphanumeric characters for phone number input field.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @SamZiemer ,

If you do not see any issues with this PR, I believe we can push it up with the following points as well (I would like the engineering team's input on the points. Let me know your analysis as well):

**A.** A full solution would be to allow +, -, # and * characters only and also alphanumeric characters.
**B.**   **A** has multiple existing issues in that AlloyUI input field we currently use for the field does not support phone Number validation. Most other implementations (Google etc) already have UI implementation in place that addresses the formatting if a user inputs country code and or special characters related to phone numbers. This part seems to fall under a feature request to me.
3. Another option is that this issue should be considered a won't fix as users should input correct formatting if they require it.

**Comment by SamZiemer** [comment]
Hi @brianikim, this fix seems like it would cause some issues with https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/format/USAPhoneNumberFormatImpl.java and https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/format/InternationalPhoneNumberFormatImpl.java

I think we should open this as a PTR rather than a PR as we do need some guidance from engineering on this issue. It may be possible to do a backend validator that validates as information is entered on the UI like we do in https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-validator/src/main/java/com/liferay/dynamic/data/mapping/validator/internal/DDMFormValuesValidatorImpl.java

With that in mind, I'll close this PR and this issue can be continued on a PTR.

**Pull request closed without merging**
