### PR TITLE
LPS-113360 Verify file store configuration

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
@SamZiemer 
How's it look?

**Comment by SamZiemer** [comment]
Hi @javalosjr96, this looks good, thank you! Forwarded to Alberto here: https://github.com/liferay-upgrades/liferay-portal/pull/297

**Pull request closed without merging**
