### PR TITLE
LPS-70065 Pass a currentURL value in the request when opening the control menu

### PR DESCRIPTION
**Pull request by SpencerWoo**
Ticket : https://issues.liferay.com/browse/LPS-70065

When a currentURL is not passed a currentURL is generated to be used as backURL.  The generated currentURL redirects to the distorted CSS page.

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @SpencerWoo,

Please make sure to assign the LPP tickets to your reviewer as well. I've done it this time, this is just for future reference.

**Comment by SamZiemer** [comment]
Hi @SpencerWoo,

After testing this fix, I do not see any difference in behavior based on the steps given on the LPS. When I click on the cancel button the page appears to reload but is still the same page. I observed no CSS errors before or after the fix, however. Can you take a look and ensure your change does what you expect if so can you post the steps you used on this pull request?

**Comment by SpencerWoo** [comment]
Hi @SamZiemer 

Alright, sorry about this.  I will look into this and let you know whether this is a correct fix.

**Comment by SpencerWoo** [comment]
Hi @SamZiemer,

Oops, I misread what you wrote in your comment, but I have now verified my change and believe it works properly / as intended.

To reproduce the issue for the LPS :
(1) Load liferay and login.
(2) Visit the homepage such that the control panel menu is closed.  If the control panel menu on the left is already closed refresh the page -- if it is open close the control panel menu on the left and refresh the page.  (The error is when in the AJAX request of opening the control panel menu).
(2) Navigation > Public Page > Configure Page
(3) Cancel

The error URL looks like 
"http://localhost:8080/web/guest/home?p_p_id=com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet&p_p_lifecycle=0&p_p_state=exclusive&_com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet_mvcPath=%2Fportlet%2Fproduct_menu.jsp&_com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet_selPpid=" 

and the webpage looks like this 
image

Let me know if anything is unclear about reproducing the bug and I'll respond quicker this time 😄

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1183

**Pull request closed without merging**
