### PR TITLE
LPS-73023

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Hi, @mbowerman, it looks like this needs to be rebased and resent.

**Comment by mbowerman** [comment]
Hi @SamZiemer,

Please see https://github.com/SamZiemer/liferay-portal/pull/301.

**Comment by SamZiemer** [comment]
Great, thanks @mbowerman!

**Pull request closed without merging**
