### PR TITLE
LPS-80609 Force to don't run the upgrade until the right store is available

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @SamZiemer 
I'm sending you back this pull so you can check the changes that I did. I coulnd't test it and it should be taken as a proposal. I would like to ensure that we don't run the upgrade until we don't have the appropriate store ready and I think that with the logic I included it should work, but as I said, I'd like you to take a look at it and see if it works.

If this approach works we should apply it not only to this upgrade in DL, but to every other upgrade using DLStore in an upgrade, such as:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/v1_0_0/UpgradeDynamicDataMapping.java#L2587
https://github.com/liferay/liferay-portal/blob/master/modules/apps/knowledge-base/knowledge-base-service/src/main/java/com/liferay/knowledge/base/internal/upgrade/v1_3_0/UpgradeKBAttachments.java#L43

Let me know if you have any doubt/question.

Thanks!
Sergio

**Comment by sergiogonzalez** [comment]
cc/ @achaparro

**Comment by sergiogonzalez** [comment]
Hey @SamZiemer do you have any update on this?

**Comment by sergiogonzalez** [comment]
Yes please. Thanks!

Sergio

**Comment by SamZiemer** [comment]
I've reset the review here with my changes https://github.com/sergiogonzalez/liferay-portal/pull/4458

**Pull request closed without merging**
