### PR TITLE
LPP-26493

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @SamZiemer,

Original Tickets:
[LPP-26493](https://issues.liferay.com/browse/LPP-26493)
[LPS-74031](https://issues.liferay.com/browse/LPS-74031)

## Main Issue
Currently, canonical URLs do not account for localization. This means that every page, regardless of which locale you are viewing it from, currently uses the same canonical URL.

For example, for the URL: http://localhost:8080
The canonical URL is http://localhost:8080

For a localized example, for the URL: http://localhost:8080/fr/
The canonical URL is currently also http://localhost:8080

This is an issue, since http://localhost:8080 and http://localhost:8080/fr/ should each have it's own canonical url. 

The expected canonical URL for this case should be: http://localhost:8080/fr/

**Note:** Below will be a section with some example scenarios to further describe expected results related to this issue

## Second Issue
Currently, alternate URLs are not being generated properly in several cases.
There was an attempt to resolve this for certain cases in [LPS-72431](https://issues.liferay.com/browse/LPS-72431).

Even then, the changes introduced did not work properly at times.
This can be seen in a recent ticket: [LPS-74272](https://issues.liferay.com/browse/LPS-74272)

The changes introduced in this pr should address generating the proper alternate URLs for the two tickets mentioned above as well.

In addition, this pr will also handle providing the proper url for the x-default hreflang tag.

**Note:** Below will be a section with some example scenarios to further describe expected results related to this issue

---
The fixes for this pr also accounts for other factors, such as:
* The portal property **locale.prepend.friendly.url.style=2**
  * The examples provided mainly focus on the overall changes.
* portal.proxy.path

Please let me know if you have any questions.
Thanks!

---

## A Few Example Scenarios - Main Issue
To better describe the goals of the fix regarding canonical URLs, here are expected results from some scenarios.

### Default Site (using default locale - en_US)
URL: http://localhost:8080
Expected Canonical URL: http://localhost:8080

URL: http://localhost:8080/en_US/
Expected Canonical URL: http://localhost:8080

URL: http://localhost:8080/web/guest/home
Expected Canonical URL: http://localhost:8080

### Default Site (using non-default locale - fr)
URL: http://localhost:8080/fr/
Expected Canonical URL: http://localhost:8080/fr/

URL: http://localhost:8080/fr/web/guest/home
Expected Canonical URL: http://localhost:8080/fr/

### Created site called testsite with second created public page testpage2 (using default locale - en_US)
URL: http://localhost:8080/web/testsite/testpage2
Expected Canonical URL: http://localhost:8080/web/testsite/testpage2

URL: http://localhost:8080/en_US/web/testsite/testpage2
Expected Canonical URL: http://localhost:8080/web/testsite/testpage2

### Created site called testsite with second created public page testpage2 (using non-default locale - fr)
URL: http://localhost:8080/fr/web/testsite/testpage2
Expected Canonical URL: http://localhost:8080/fr/web/testsite/testpage2

## A Few Example Scenarios - Second Issue
To better describe the goals of the fix regarding alternate URLs, here are expected results from some scenarios. For these examples, we will only include a snippet of the hreflang tags to reduce the amount of space used.

### Default Site (using default locale - en_US)
URL: http://localhost:8080/web/guest/home
```
<link data-senna-track="temporary" href="https://localhost:8080/fr/" hreflang="fr-CA" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080" hreflang="x-default" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080" hreflang="en-US" rel="alternate">
```

### Default Site (using non-default locale - fr)
URL: http://localhost:8080/fr/web/guest/home
```
<link data-senna-track="temporary" href="https://localhost:8080/fr/" hreflang="fr-CA" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080" hreflang="x-default" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080" hreflang="en-US" rel="alternate">
```

### Created site called testsite with second created public page testpage2 (using default locale - en_US)
URL: http://localhost:8080/web/testsite/testpage2
```
<link data-senna-track="temporary" href="https://localhost:8080/fr/web/testsite/testpage2" hreflang="fr-CA" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080/web/testsite/testpage2" hreflang="x-default" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080/web/testsite/testpage2" hreflang="en-US" rel="alternate">
```

URL: http://localhost:8080/en_US/web/testsite/testpage2
```
<link data-senna-track="temporary" href="https://localhost:8080/fr/web/testsite/testpage2" hreflang="fr-CA" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080/web/testsite/testpage2" hreflang="x-default" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080/web/testsite/testpage2" hreflang="en-US" rel="alternate">
```

### Created site called testsite with second created public page testpage2 (using non-default locale - fr)
URL: http://localhost:8080/fr/web/testsite/testpage2
```
<link data-senna-track="temporary" href="https://localhost:8080/fr/web/testsite/testpage2" hreflang="fr-CA" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080/web/testsite/testpage2" hreflang="x-default" rel="alternate">
<link data-senna-track="temporary" href="https://localhost:8080/web/testsite/testpage2" hreflang="en-US" rel="alternate">
```

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by ericyanLr** [comment]
Hi @SamZiemer,

I just received a comment from a related ticket: [LPS-74272#comment-1097963](https://issues.liferay.com/browse/LPS-74272?focusedCommentId=1097963&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1097963)
It looks like it would be best to include integration tests with this fix.

I'll be working on adding the integration tests, should I close this pr?
Thanks!

**Comment by SamZiemer** [comment]
Hi Eric, yeah go ahead and close this PR and re assign the tickets to yourself while you work on the integration tests, thanks for letting me know!

**Comment by SamZiemer** [comment]
ci:stop

**Pull request closed without merging**
