### PR TITLE
LPS-72654 Updating DXP KB build number to 20 putting it ahead of 6.2

### PR DESCRIPTION
**Pull request by joshuacords**
As per a recommendation from Minhchau Dang, I will be increasing KB's build number to 20. This brings master ahead of the plugins-ee build number (it was incremented incorrectly in LPS-67188). This also brings master's build number forward as it should have been after LPS-57585 and adds a bit of a buffer between plugins-ee and master.

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hey @joshuacords, can you please link to the commit where the incorrect build number occurred in plugins-ee.

**Comment by joshuacords** [comment]
@SamZiemer this is where the service build number was increased when there were no changes to the database schema: https://github.com/liferay/liferay-plugins-ee/commit/08038ccc2740c6476320a7a58a8135bd8bc670f4#diff-2beb4fd4dd854c134b258956a9e1abbe

**Comment by SamZiemer** [comment]
Thanks @joshuacords

**Comment by SamZiemer** [comment]
Hi, @joshuacords,

After some discussion with the higher up reviewers, I do not believe this is th

**Pull request closed without merging**
