### PR TITLE
LPS-92509

### PR DESCRIPTION
**Pull request by brianikim**
Redirected from: #574

cc/@matthewchan123

Note from Matthew: https://github.com/SamZiemer/liferay-portal/pull/574#issue-266677644

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @SamZiemer ,

Apologies for the multiple PRs. I have CI set up for liferay-portal now so ci:test issues should be caught on my end before being directed to you for future PRs.

Sincerely,
Brian Kim

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/achaparro/liferay-portal/pull/290

**Comment by SamZiemer** [comment]
ci:stop

**Pull request closed without merging**
