### PR TITLE
LPS-73315 Change notification to display remaining days until expiry

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPP-26060
https://issues.liferay.com/browse/LPS-73315

We change the notification of password expiry to inform the user how soon their password will expire and account locked (requiring administrator contact).

ant build-lang automatic copies our language key because of https://github.com/liferay/liferay-portal/blob/master/modules/util/lang-builder/src/main/java/com/liferay/lang/builder/LangBuilder.java#L393.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
hi @SpencerWoo,

It looks like you need to increase the bundle version of portal-impl with this change as you are adding a new public method to the api. However, I don't think we need to go that route since you are only using the isPasswordExpiringSoon method in 1 place in LoginPostAction.java, you can instead just make it a private or protected method in that class. This will avoid the needless bundle version increase.

Let me know if you have any questions thanks,
Sam

**Pull request closed without merging**
