### PR TITLE
LPS-71134

### PR DESCRIPTION
**Pull request by Alec-Shay**
Re-sending from https://github.com/SamZiemer/liferay-portal/pull/208

Copying notes from previous pull:

> Relevant tickets:
> 
> https://issues.liferay.com/browse/LPP-24513
> https://issues.liferay.com/browse/LPS-71134
> 
> As a result of LPS-57516, a bug was exposed where importing Wiki nodes using the default "Mirror" import strategy would not work because it cannot handle name conflicts the same way other components can, despite code for it already being in place. This fix is leveraging the existing getNodeName() method to create a new name to avoid name conflicts when importing with the default "Mirror" strategy.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1250

**Comment by Alec-Shay** [comment]
Thanks, Sam!

**Pull request closed without merging**
