### PR TITLE
LPS-105754 SF

### PR DESCRIPTION
**Pull request by achaparro**
Hey @SamZiemer, are you ok with these changes?

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hi @achaparro,

I think these changes make sense, thank you. Would you like me to send these to Brian Chan, or would you prefer to forward it on?

**Comment by achaparro** [comment]
Hi @SamZiemer,

I have sent the pull to Brian, I have included the logging timer too.
https://github.com/brianchandotcom/liferay-portal/pull/82079

Thanks!

**Pull request closed without merging**
