### PR TITLE
LPS-70087

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by SamZiemer** [comment]
hey @mbowerman,

Do you have any sort of steps to test this change? If so, can you please post them on the LPS ticket.

**Comment by mbowerman** [comment]
Hey @SamZiemer,

This is just a performance improvement ticket, not a bug fix. Are steps still needed in this case?

The idea is that now, when we call hasOtherAssignees, we stop and return true as soon as we determine it has one other assignee. Before, we were getting the entire pool of assignees (which can be quite time-consuming), and then checking if the pool contained an assignee other than the user.

I tried testing that the logic for hasOtherAssignees still worked properly by creating a workflow task for the Single Approver workflow and going to the My Workflow Tasks > Assigned to My Roles page. I verified that the "Assign To..." link didn't appear. Then I added another admin user and revisited the page. This time, I verified that the "Assign To..." link did appear.

**Comment by SamZiemer** [comment]
hey @mbowerman,

We need at least the steps to get to the page where the slowness occurs so QA can test the issue once the PR is reviewed.

**Comment by SamZiemer** [comment]
Hi @mbowerman,

Any update on this?

**Comment by mbowerman** [comment]
Hi @SamZiemer,

I've added some reproduction steps to the LPS. Please take a look.

**Comment by SamZiemer** [comment]
Thanks @mbowerman, these steps help

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1182

**Pull request closed without merging**
