### PR TITLE
[TECHNICAL-SUPPORT] LPS-107322

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/achaparro/liferay-portal/pull/445

**Pull request closed without merging**
