### PR TITLE
LPS-82764

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-30461
https://issues.liferay.com/browse/LPS-82764

If LDAP users are imported into multiple environments, exporting and importing data between these environments will not maintain ownership by those users. This is because the users will most likely have differing userId's between these environments, and UUID (unlike userId) is no longer included in the StagedModel itself for export/imports.

This is caused by [LPS-44571](https://issues.liferay.com/browse/LPS-44571), which removed user UUIDs from the StagedModel used in LAR exports so that there is no way left for Liferay to identify the users with UUID. On [the SME subtask opened for this issue](https://issues.liferay.com/browse/LPP-30532), it was noted that we would need to find another way to do it, probably as with the `asset-entry-priority` attribute. Thus, this fix instead adds it to the containing data element in the LAR rather than the StagedModel itself.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
@SamZiemer Still checking as to where this PR should go from here. We are waiting on the confirmation as to whether we'll need an SDH, though.

**Comment by Alec-Shay** [comment]
Closing for now due to the freeze in master

**Comment by SamZiemer** [comment]
Hi @Alec-Shay This fix looks good to be moved forward, once the code freeze has been lifted please send this forward to Eudaldo Alonso, github name of ealonso.

**Comment by Alec-Shay** [comment]
Sounds good to me. Thanks @SamZiemer!

**Comment by matethurzo** [comment]
hey guys, not meaning to interrupt, but i think it would be me who can review these changes, this is 100% staging code. also we have been classified this as something we want to fix for 7.1 as well soon, so you can send it to me at your earliest convenience

**Comment by Alec-Shay** [comment]
Sent to https://github.com/matethurzo/liferay-portal/pull/2163.

Thanks @matethurzo for letting us know about the classification.

**Pull request closed without merging**
