### PR TITLE
[TS]LPS-160305 Check if type is null, continue upgrade if null

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:[LPS-160305](https://issues.liferay.com/browse/LPS-160305)

Issue:
If a Forms field is removed after entries are already added for that form, then during the upgrade when attempting to get the field's type, will throw a null exception since the field no longer exists on the form.

Solution:
We determined that the upgrade process should still continue even if the form field no longer exists in the form.  The entry will still be added to the database to retain that data even though the portal/user will not be able to view it from the portal.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hi @javalosjr96 The fix looks good but please send this fix, and future fixes to the Liferay-uniform user. I will forward it from there.

**Comment by javalosjr96** [comment]
@SamZiemer 
Hey Sam,
sorry about that I forgot to do that.

**Pull request closed without merging**
