### PR TITLE
Lps 68877

### PR DESCRIPTION
**Pull request by gregory-bretall**

### CODE REVIEW

**Comment by gregory-bretall** [comment]
Just a note that I accidentally left some excess code in my pull request that doesn't do anything anymore, should I resend a PR with it removed?

**Comment by SamZiemer** [comment]
You don't need to send a new PR, but you can update this branch and let me know once you have done that.

**Comment by gregory-bretall** [comment]
I've updated the branch to reflect the new changes

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1118

**Pull request closed without merging**
