### PR TITLE
LPS-130815 Filter and Order should persist.

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-130815

See LPS-130815 for issue description.

The reason this issue occurs is because the settings are never persisted and are not contained within the request. The changes made to orderByCol and orderByType are saved through portalPreferences and we should use it to make sure the changes are always reflected.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @SamZiemer ,

Test results look good. Let me know if you see any issues with the implementation.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/drewbrokke/liferay-portal/pull/1345

**Pull request closed without merging**
