### PR TITLE
LPS-77842

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPS-77842

The Repository table in the database has both a name and portletId column, and Liferay at times expects to put the same value in both columns. However, with long portletId's (which have a limit of 200 characters), adding a row will fail because the name column can only hold 75 characters.

[LPS-35711](https://issues.liferay.com/browse/LPS-35711) extended the size of the portletId column, but not the name column. From the description, it looks like this was done to allow it to match the size of portletId columns in other tables. Additionally, we found through investigating the code that there are some places in the code that expect to put the same value into each of these columns or for them to be the same (for example, see [PortletFileRepositoryImpl](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/portletfilerepository/PortletFileRepositoryImpl.java#L270-L274)). Thus, we believe this is an oversight that can be treated as a bug.

In my testing, I faced issues with the Service Builder that prevented me from generating the changes to update the schema. Because of this, the changes to the Repository table that would resolve this issue were not reflected in my testing. I was following this documentation, and faced errors with the last step that seem to be specific to my environment: https://grow.liferay.com/people/Modifying+Liferay+Core+schema

Can these extra changes be added in? Thanks in advance!

Of course, please also let me know if there are any concerns about this fix. Thank you.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
@SamZiemer This is the fix I mentioned before that the Loop team wants a fix for, so there's no associated LPP (as of now). Let me know if you have any questions though. Thanks.

**Comment by Alec-Shay** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/sergiogonzalez/liferay-portal/pull/4217

**Comment by SamZiemer** [comment]
ci:stop

**Pull request closed without merging**
