### PR TITLE
LPS-121301

### PR DESCRIPTION
**Pull request by brianikim**
Notes from @noornajj:

> https://issues.liferay.com/browse/LPS-121301
> 
> The issue here was that the redirect was being overwritten by a newly generated URL.
> To fix the issue, I deleted the code that is creating the URL and had getRedirect return the redirect from the actionRequest.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
Hello @SamZiemer, are there any updates on forwarding this PR?
Thank you

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/liferay-echo/liferay-portal/pull/2521

**Pull request closed without merging**
