### PR TITLE
LPS-91536 Only try to add 1 AssetDisplayPageEntry per index

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-91536
https://issues.liferay.com/browse/LPP-33125

**Problem**: The upgrade process tries to add a AssetDisplayPageEntry for each journal article version, however only one AssetDisplayPageEntry should exist for all versions of a journal article. What happens is after the first version creates an AssetDisplayPageEntry, all remain versions will through benign errors during the upgrade process.

**Solution**: Since only one AssetDisplayPageEntry is necessary for each journal article set of versions, and there is no differentiation in linkage between any of the version, I use a Set to only try adding the first version.

Note: In master, this upgrade process will also throw errors because of https://issues.liferay.com/browse/LPS-91537. This fix will remove the duplicate index errors, but not the errors documented on that ticket. In 7.1.x, those other errors don't exist and so this fix will remove all errors.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hey @joshuacords,

I don't think this is the right approach to resolve this issue. Rather than grab up all versions in our initial query then iterating over all of them, it would be better to just grab a single row from each version. This also could give a slight performance benefit by iterating over potentially far fewer rows retrieved from the database.

Let me know if you have any questions.

**Comment by joshuacords** [comment]
Hi @SamZiemer,

I thought about that, but I didn't know of a way to uniquely grab results based on an index. Do you have a suggestion on how to do that?

**Comment by SamZiemer** [comment]
You can add to the sql "group by resourcePrimKey" or something similar. There may other instances where we do that in the portal as well. Essentially all that does is show you a single unique row per resourcePrimKey, and in this case, all we care about are the groupId, userId, and resourcePrimKey which should all be the same or, in the case of userID, not matter all that much if it isn't the same. Another option would be to pull the max version from journal article... similar to how it is done [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/upgrade/v0_0_7/UpgradeJournalArticleDates.java#L75-L85). Note, that link also uses group by

**Comment by joshuacords** [comment]
Resent here: https://github.com/SamZiemer/liferay-portal/pull/564

**Pull request closed without merging**
