### PR TITLE
Lps 65584

### PR DESCRIPTION
**Pull request by Alec-Shay**
Using Validator's isNotNull() when creating a search display context will cause a NullPointerException when trying to render the results, since it expects an object to be able to get the hits from but IsNotNull() treats the word "null" as actually null. This causes the searchDisplayContext to not be properly initialized.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
@SamZiemer    Sorry I didn't run the format source before I'd already pushed this, I was having problems with it and only learned how to get around it after the fact.

However, I have no idea what it's complaining about with the parentheses. Any ideas?

**Comment by Alec-Shay** [comment]
@SamZiemer   Never mind, it should be good now. Sorry about that.

**Comment by SamZiemer** [comment]
Hey @Alec-Shay 

I was looking into this a bit and found that our web content search portlet seems to work fine when searching null prior to your fix. This leads me to believe we have handled it somewhere in web content search portlet but did not make an equivalent fix for the regular search portlet. Both searches go through the SearchDisplayContext.java constructor. I believe a better fix would be to incorporate the same logic that make the web content search portlet work as desired.

Let me know if you have any questions.

**Comment by Alec-Shay** [comment]
Hi @SamZiemer,

I took a second look at this, and although it's true that the other search-related portlets also create a SearchPortletContext, it's for different reasons. The portal search portlet creates this because it uses a faceted search, and it needs the context to initialize the weights of the facets (the SearchDisplayContext's constructor initializes them), whereas it doesn't seem like the other portlets care too much whether it keeps null values.

Without the SearchDisplayContext being initialized correctly, the search portlet will not be able to sort by the facets; I suppose there could be an extra check added for, if the facets are null, not sorting the facets, but I think that may cause unexpected behavior as a regression. In any case, I think that the facets remaining uninitialized in this spot is a bug and the null check should be changed to adjust for this.

Can you take another look at this? Thank you.

**Comment by SamZiemer** [comment]
Hi @Alec-Shay, thanks for looking into that further I will forward on your notes.
https://github.com/jonathanmccann/liferay-portal/pull/981

**Comment by Alec-Shay** [comment]
Thanks, @SamZiemer.

**Pull request closed without merging**
