### PR TITLE
[TECHNICAL SUPPORT] LPS-72431 Prepend language ID in canonical URL if property is applied

### PR DESCRIPTION
**Pull request by thomasstew**
Relevant ticket:
[LPS-72431](https://issues.liferay.com/browse/LPS-72431)

The canonical url does not adhere to the url format when a particular friendly url style property is applied.

This fix prepends the language id to the canonical url if the property is applied, as well as modifying the logic of getting the alternate urls to split the canonical url in the correct place.

Let me know if you have any questions!

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @thomasstew,

Please run the source formatter and resend the pull request. Ensure the code follows the [code guidelines](https://web.liferay.com/community/wiki/-/wiki/Main/Development+Style) before resending, also please note, when running the source formatter not all issues are resolved automatically. There are times when there will be error output on the command line.

**Comment by thomasstew** [comment]
Hi @SamZiemer,

It looks like the formatter failed because of /modules/apps/foundation/portal-security/portal-security-wedeploy-auth-web/src/main/java/com/liferay/portal/security/wedeploy/auth/web/internal/portlet/action/WeDeployAuthorizeUserMVCActionCommand.java, right?

I did not modify that file, so I'm not sure why it would be failing because of that.

**Comment by SamZiemer** [comment]
ah, I must have misread that, thanks. I'll reopen this pull.

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Hey @thomasstew,

In the LPS it mentions some of the URLS are working correctly. What is causing those URLs to be built with the correct language style while others are not? Since before this change, something was building them correctly. I think we should try to determine what that was.

Also, can you please update the LPS ticket to show steps to reproduce for master rather than 62, QA uses the LPS ticket for testing our fixes and they need to reflect the current version of liferay.

**Comment by thomasstew** [comment]
Hi @SamZiemer,

The URLs that are working correctly are the alternate urls (see the _getAlternateURLs() method in PortalImpl.java). That method generates the correct URLs because it checks the particular property for prepending a language id. 

The URLs that are not working correctly are the canonical URLs. The canonical URL is currently not checking the value of this property, so a language id is not being prepended. 

This fix has 2 parts to it:
1. Check the property value when getting the canonical URL, so the language id is properly prepended
2. Modify how the alternate URLs are generated, because they are based off of the canonical URL - so the _getAlternateURLs() method is not expecting the canonical url to have a language id already in it

Also, I have updated the the steps to reproduce in the LPS.

Let me know if this answers your questions.

Thanks!

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/rotty3000/liferay-portal/pull/1311

**Pull request closed without merging**
