### PR TITLE
LPS-68572

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @mbowerman,

Why do we need to remove the entries from the map rather than keep them in the map with get?

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1086

**Comment by mbowerman** [comment]
Hi Sam,

Later on, we check if we have gotten/removed all the map entries or not with a call to map.isEmpty(). If we have not, then we do something with the remaining entries. I couldn't find a better way to do this than to call map.remove on a copy of the map.

**Comment by SamZiemer** [comment]
Yeah, I actually realized that after I asked the question. I could not think of another way to do it myself, so I forwarded it on to Jonathan.

**Pull request closed without merging**
