### PR TITLE
LPS-92362 Take into account portalContext for OpenId URI

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-92362
https://issues.liferay.com/browse/LPP-33333

Problem: The URI created for OpenId Connect doesn't add the Path Context, but other parts of the portal handle a different path context appropriately.

Solution: Add the path context, which will normally be blank unless the tomcat bundle is modified.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/stian-sigvartsen/liferay-portal/pull/146

**Pull request closed without merging**
