### PR TITLE
LPS-71385

### PR DESCRIPTION
**Pull request by Alec-Shay**
/cc @moltam89

Relevant tickets:

https://issues.liferay.com/browse/LPP-24582
https://issues.liferay.com/browse/LPS-71385

If an Application Display Template is added using a Page Template, then if a page based on it is exported and imported to a separate environment (the Page Template must be imported as well), then the Application Display Template can no longer be used for portlets on the imported page; there are also various inconsistencies with when these can be selected for the portlets, also related to this issue (should be resolved by these changes).

When a Page Template is created and ADT's are added through portlets on the page, they are added to the scope group of that Page Template; however, this appears to be unintentional, as ADT's cannot be added to Page Templates normally, and this case is not handled when exporting/importing the same way as for Site Templates (for Site Templates, any site based on it will have its data copied, including ADT's, avoiding any confusion by replicating the data with the new site).

After some discussion, although the pattern is not clearly defined, we concluded using the Global site for ADT's from Page Templates makes the most sense, as it is not only a fairly simple solution, but seems that it could be the only way to handle this case in a way applicable to 6.2 as well (in 6.2, this kind of dependency between sites would only work between environments for the Global site). Given that they work differently from Site Templates, and you cannot normally create ADT's for a Page Template, it still seems consistent with the pattern in place, too.

Note that two places in the code needed to be changed for this to look and work consistently:

1 - `PortletDisplayTemplateDDMDisplay.getTemplateGroupIds()` is used when searching the ADT's in the "Manage Application Display Templates" menu for portlet configuration
2 - The `ddmTemplateGroupId` in `template_selector/page.jsp` seems to separately determine what group new ADT's are added to (used in the `Liferay.Util.openDDMPortlet()` call near the bottom), so it needs to be changed separately

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hey Alec, when I run format source, I see the following error, can you look into it?

>Use @Reference instead of calling GroupLocalServiceUtil directly, see LPS-59076: ./modules/apps/web-experience/portlet-display-template/portlet-display-template-web/src/main/java/com/liferay/portlet/display/template/web/internal/dynamic/data/mapping/util/PortletDisplayTemplateDDMDisplay.java

**Comment by Alec-Shay** [comment]
@SamZiemer Thought I ran it before, missed that somehow. I think I know how to fix it, mind if I just force push it back here after I test it?

**Comment by SamZiemer** [comment]
That will work, just let me know once you push up the change.

**Comment by Alec-Shay** [comment]
Pushed up https://github.com/SamZiemer/liferay-portal/pull/218/commits/90aa7ad596ebda943a50f28260b10a01f1b58a91. That should work.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1267

**Pull request closed without merging**
