### PR TITLE
LPS 82717

### PR DESCRIPTION
**Pull request by brianikim**
Hello @SamZiemer ,

https://issues.liferay.com/browse/LPS-82717

The issue is that DLAppUtil's getExtension is passing in the Title to be checked for an extension if a sourceFile does not exist. The logic here is flawed because a Title of a document entry should never be used for checking extensions because no source Files exist. Because the logic exists, it is causing variety of issues that are described in LPS-82717.

The simple fix is to remove the use of Title being checked for extensions and/or mimeTypes.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
hey Sam. This looks more of an issue with Ci:Test so I will run the test one more time

**Comment by brianikim** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Hi @brianikim, pending the results of the tests that are currently running you should be ok to move this fix forward after the code freeze has been lifted.

In the future on pull requests, please run tests using the ci:test:relevant and ci:retest:relevant commands, QA posted [here](https://loop.liferay.com/home/-/loop/feed/11056878) on the reasons behind using these newer commands.

**Pull request closed without merging**
