### PR TITLE
LPS-93227 Add 'X' to alert danger banner

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-93227
Previous pr: https://github.com/marcoscv-work/liferay-portal/pull/172

Merged into Master and then failed QA. I changed the button's visibility style to use `aui` tag-lib instead of implementing it on the jsp end.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonmak08/liferay-portal/pull/2067

**Pull request closed without merging**
