### PR TITLE
LPS-69040

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hey @mbowerman,

Can you look at the source formatter errors?

Also, I tried testing your fix but could not delete any sort of calendar event and received this message

"Access denied to com.liferay.calendar.service.CalendarBookingService#deleteCalendarBookingInstance" Is this related to your fix?

**Comment by mbowerman** [comment]
Hi Sam,

I looked at the source formatter error but it appears to be unrelated to my changes. It appears to be the result of changes that were made recently to users-admin-web/bnd.bnd. Could we try reopening the pull request and rerunning the ci test?

I didn't see that error that you mentioned. I was able to delete calendar bookings just fine in my testing.

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
HI @mbowerman,

It seems the issue I was having deleting events was something in my own environment. The source formatter errors also do not appear to be related to your fix. I've forwarded it to https://github.com/jonathanmccann/liferay-portal/pull/1114

**Pull request closed without merging**
