### PR TITLE
[TS] LPS-99216 Add required to ddm image descriptions

### PR DESCRIPTION
**Pull request by matthewchan1**
https://issues.liferay.com/browse/LPS-99216

Issue:
Image Description field should have validation when the Web Structure field is configured to "required".

Fix:
I simply adjusted the Image Freemarker Template to allow this setting.

### CODE REVIEW

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
ci:stop

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hey @matthewchan1, I think we need to add the asterisk when creating the structure as well as when it is used in a web content. see the screenshot:
image

**Pull request closed without merging**
