### PR TITLE
LPS-104676 Unhelpful validation error message when publishing web content with missing document link

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-104676

**Issue**:
If a link between a Documents & Media file and a Web Content Article is invalid, when attempting to publish, the error displayed isn't helpful to non-technical authors.
`Error: Unable to validate referenced file entry because it cannot be found with the following parameters: {groupId=[20118], uuid=[0e3af03d-3c94-2cd7-f2f7-2cb1016ee488], endPos=[322]}.`

**Solution**:
This fix updates the error message to include the document and media reference link that is associated with the error. [DLReferenceExportImportContentProcessor.getDLReference](https://github.com/SamZiemer/liferay-portal/compare/master...knchau:LPS-104676?expand=1#diff-e02a1e5d12728441cc3c53cdeaa6b2e6R132) crops the content string to the document's link, which is used to set the `dlReference` so it can be seen in the error message. This makes the error clearer because it specifies that the analyzed link has a problem (which is what flagged the error). 

Note: still needs to be translated.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/adolfopa/liferay-portal/pull/1166

**Pull request closed without merging**
