### PR TITLE
Lps 113360

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
@SamZiemer 
I'll fix the sf issue and versioning shortly.

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hi @javalosjr96, the code changes look good, however I am not sure why the semantic versioning change for portal-kernel/src/com/liferay/portal/kernel/portlet/constants was changed. I don't think that is needed for this fix so please remove that and I will forward this on.

**Comment by SamZiemer** [comment]
ci:close

**Pull request closed without merging**
