### PR TITLE
LPS-153804 - Change in status check in Workflow

### PR DESCRIPTION
**Pull request by Gabriel422-hue**
Related Issue: https://issues.liferay.com/browse/LPS-153804

Hello Sam!
I'm including it in the check, if the status is pending as being rejected, it can edit and resubmit

### CODE REVIEW

**Comment by Gabriel422-hue** [comment]
ci:test:sf

**Comment by Gabriel422-hue** [comment]
ci:test:relevant

**Comment by Gabriel422-hue** [comment]
ci:test:relevant

**Comment by Gabriel422-hue** [comment]
ci: stop

**Comment by Gabriel422-hue** [comment]
ci:stop

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/liferay-forms/liferay-portal/pull/2042

**Pull request closed without merging**
