### PR TITLE
LPS-102798

### PR DESCRIPTION
**Pull request by brianikim**
@katienesterovich 's notes:

> Ticket: https://issues.liferay.com/browse/LPS-102798
> 
> Caused by: https://issues.liferay.com/browse/LPS-96828
> 
>     
>  mvcRenderCommand and urlTitle parameters were not passed up as they did not contain "INSTANCE_0_" in the name (`_com_liferay_blogs_web_portlet_BlogsPortlet_urlTitle` vs `_com_liferay_blogs_web_portlet_BlogsPortlet_INSTANCE_0_urlTitle`). The portlet namespace `_com_liferay_blogs_web_portlet_BlogsPortlet_INSTANCE_0_` did not prepend the parameters (i.e. they were not namespaced), causing the params to bypass the dynamicRequest parameter addition. As a result, the parameters could not be used and links redirected user back to the /blogs/view page.
> 
> 
> Fix: If portlet is non-instanceable and portletNamespace contains "INSTANCE_0_" while parameter does not, inject "INSTANCE_0_" into the parameter name.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/Preston-Crary/liferay-portal/pull/897

**Comment by SamZiemer** [comment]
Hi @katienesterovich, @brianikim,

I had a conversation with Preston regarding this issue. This does not appear to be the right way to go about fixing this issue. PortletRequestImpl.java can get called many many times for each page load, and the requests being checked are not exclusive to this one issue. It would be better to look at https://issues.liferay.com/browse/LPS-96828 to see how these urls are generated and fix this issue closer to that source, rather than in PortletRequestImpl that is called from all over the portal.

**Comment by brianikim** [comment]
Thank you @SamZiemer , @katienesterovich  will work on the issue again.

**Pull request closed without merging**
