### PR TITLE
LPS-125591

### PR DESCRIPTION
**Pull request by brianikim**
Resending from https://github.com/SamZiemer/liferay-portal/pull/774

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/achaparro/liferay-portal/pull/792

**Pull request closed without merging**
