### PR TITLE
LPS-71943

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-25158
https://issues.liferay.com/browse/LPS-71943

The Dynamic Data Lists Display portlet's configuration does not check any group other than the current group for Display or Form Templates. This fails to match the pattern of other portlets that also check the Global site and parent sites.

This change just retrieves the Templates for all of these sites as well and checks them all, if the user has "View" permissions. The API to check multiple groups while limiting to a single type of Template is not available in `DDMTemplateLocalServiceUtil`, so the list must be created manually (I think it's more efficient performance-wise to do it that way than iterating over every Template, even if the type doesn't match).

Please let me know if there are any problems with this. Thanks.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:restart

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:restart

**Comment by Alec-Shay** [comment]
@SamZiemer I just looked at it, and from what I can tell, manually created templates seem to always have the "create" mode. I'm not really sure why this constant is necessary, but I guess it's fine as is (seems like it was something form templates support that was added in on its own). That was added in with this commit: https://github.com/liferay/liferay-portal/commit/ee88891e603c9b3d982780090b5d771c5f994a4a

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1292

**Pull request closed without merging**
