### PR TITLE
LPS-94690 Async status monitoring for remote staging

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-94690

Previous pr: https://github.com/moltam89/liferay-portal/pull/504
Changes due to [PTR-1005 discussion](https://issues.liferay.com/browse/PTR-1005?focusedCommentId=1925083&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1925083).

The issue is when the site is staging. At every page load of the Control Panel, the local server would send a request to the remote server. This can cause the site to hang because the request is sent in GroupServiceHttp.getGroupDisplayURL. The timeout can take 30 seconds.

The solution is to cache the result for Remote Staging, when the Control Panel is navigated (based on last-updated-time type of approach). The groupDisplayURL will be cached for each staged site and stored within the TypeSettings. If Control Panel is navigated and the last-updated-time is still relevant, we will provide the cached remote URL. If the cached value is expired, user would request the URL and cache the value again. 

Race-conditions are handled by utilizing a strategy that is being used for merging layoutset prototypes in [SitesImpl.java#L1319](https://github.com/liferay/liferay-portal/blob/7.2.0-ga1/portal-impl/src/com/liferay/portlet/sites/util/SitesImpl.java#L1319).

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/moltam89/liferay-portal/pull/526

**Pull request closed without merging**
