### PR TITLE
[TS] LPS-118902 Portlet ID references in custom css not upgraded from 6.2

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @SamZiemer, I'm sending this pr to the upgrade team although I'm not sure which other team should review its semantics. Please redirect me if you believe another team should review it instead. 

The issue to solve by this pr is the outdated references to portlet id's when upgrading from 6.2 (or 6.1) to 7.0 and above due to the extensive renaming from numerical to fully qualified identifiers. The current upgrade makes sure to replace the portletId in PortletPreferences but won't touch css references in the preferences. 

These references to the portlet id's may be there or not because it's up to the user to use them, but if they choose to do so, they must be the id's specified by Liferay. This pr updates the css references starting with the string '#portlet_'. 

The main changes are all done in a single method, except for a couple of cases where this method is overridden and the code has to be adapted accordingly. 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:sf

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:forward

**Comment by SamZiemer** [comment]
Hi @ricardocousolr,

these changes look good, thank you!

**Pull request closed without merging**
