### PR TITLE
LPS-73023

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
Hi @SamZiemer,

I forgot to mention, please pass along the message not to automatically backport this when it gets committed to master, since it has not yet been tested on the databases not supported in master.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1344

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
ci:close

**Pull request closed without merging**
