### PR TITLE
[TECHNICAL SUPPORT] LPS-72368 Revert to default LayoutSet to avoid repeating errors

### PR DESCRIPTION
**Pull request by JoshuaStClair**
[LPS-72368](https://issues.liferay.com/browse/LPS-72368)
When themeLocalServiceImpl:getTheme is called, but the theme cannot be found (usually because it was undeployed while configured), the theme will revert to the default Liferay theme and [WARN messages will appear in the console notifying the developer](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/ThemeLocalServiceImpl.java#L231). However, the reversion is never persisted so if you refresh the page, this message will continue to flood the log with every refresh. Even though the page has already reverted, it will keep trying to get the theme that is no longer there. The only way to stop this is to reconfigure the page from the control panel and set it to another theme. Even then, the control panel will show that the default Liferay theme is set, even though the error messages continue to appear. Ideally, we should persist the reversion right after the WARN messages but we need to call updateLookAndFeel for the LayoutSet and that requires a groupId which we don't have in ThemeLocalServiceImpl. Thus, the next best alternative is calling it in the caller function one level up the stack, in LayoutSetImpl. After this update, successive calls will query the default Liferay theme instead of the undeployed theme and no more WARN messages will appear.

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @JoshuaStClair This is a change that we cannot implement into the portal. This is actually very similar to a ticket worked on a [few weeks ago](https://issues.liferay.com/browse/LPP-25335?focusedCommentId=1023132&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1023132). Imagine if a developer changed their theme, introduced a bug, and it didn't deploy correctly? We shouldn't just change their theme automatically without telling them, forcing them to recognize something went wrong and then have to change their site's theme back to what they want.

Let me know if you have any questions,

Sam

**Comment by JoshuaStClair** [comment]
Hi @SamZiemer, my thought process with this change was that we should align the error messages with what the developer sees in the portal. If the developer sees that the theme has been reverted to the default theme due to an error or undeployment, and it is reflected in the control panel that the theme is now set to the default theme, then he/she would think it has been reverted. However, every time he queries the page, refreshes, etc. the WARN messages continue to flood his console even though the portal seems the reflect it has already reverted. ( _"[ThemeLocalServiceImpl:230] No theme found for specified theme id spaceprogramtheme_WAR_spaceprogramtheme. Returning the default theme."_ is shown 8 times for every refresh.) This issue being brought up more than once reveals that it is a bit unclear if this is expected.

**Comment by SamZiemer** [comment]
Hi @JoshuaStClair, While I understand your point of view, I do not believe we should change this. I see no reason for reverting to the default theme the first time a theme can not be found. For example, when developing a theme if an error occurs the theme is immediately reverted, so to redeploy the theme, a developer must redeploy, then switch it in the control panel, this is an unneeded additional step. Another example is upgrading, if the theme is not deployed after the upgrade, the theme would be switched without warning or context.

If the logging is too much, a client can simply change the logging levels to not show the warn messages.

**Comment by JoshuaStClair** [comment]
Understood. I will let the client know. Thanks for the feedback!

**Pull request closed without merging**
