### PR TITLE
LPS-71088 Made Preview Container of Web Content Fluid

### PR DESCRIPTION
**Pull request by joshuacords**
Same goal as LPS-70705, I didn't properly test a change that was made to that PR which made it not a solution for that ticket. This ticket solves the problem while maintaining the Lexicon.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci: reopen

**Comment by joshuacords** [comment]
ci: retest

**Comment by joshuacords** [comment]
ci:reopen

**Comment by joshuacords** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1249

**Pull request closed without merging**
