### PR TITLE
LPS-87348 Default Drag&Drop behavior should be disabled when AlloyEdi…

### PR DESCRIPTION
**Pull request by brianikim**
…tor is present

### CODE REVIEW

**Comment by brianikim** [comment]
https://issues.liferay.com/browse/LPS-87348

Hello @SamZiemer ,

The issue here is that, browsers will by default try to download or open files. 

This default behavior of browsers become an issue when a user is creating content or editing existing content through Liferay's AlloyEditor. If a user drops a media file, for ex. an image or a video, but accidentally drops the said file into non-editable areas where AlloyEditor's drag&drop listeners are not triggered, the default browser behavior will be triggered and the file will be opened in the browser.

The problem with this is that users will lose all unsaved progress.

My fix is an implementation of the suggestion made here: https://github.com/liferay/alloy-editor/issues/903#issuecomment-439182232. If a file is dropped in non-editable areas, an alert will ask the user whether they would like to proceed and warn that unsaved changes will be lost.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @SamZiemer ,

I was not able to get the translations working.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

**Comment by SamZiemer** [comment]
Hey Brian, please resolve the conflicts with the language file.

In addition, I think the language key and statement could be reworked a bit, this sounds clunky.

Maybe something like "Are you sure you want to navigate away? Any unsaved changes will be lost."

When doing a 2 part language key, you can use just the first sentence, so it could be "are-you-sure-you-want-to-navigate-away" This will help keep it a bit shorter and easier to bring into the portal for future uses.

**Pull request closed without merging**
