### PR TITLE
LPS-73430

### PR DESCRIPTION
**Pull request by ericyanLr**
Original Tickets:
[LPP-25030](https://issues.liferay.com/browse/LPP-25030)
[LPS-73430](https://issues.liferay.com/browse/LPS-73430)

Hi @SamZiemer,
The main goal for this pr is to make sure the Accessibility attribute, **aria-invalid**,  is set properly. 
In order to accomplish this, each field is now also validated during an onblur event.

The changes, for the most part, are refactoring changes for the current validation code.
The approach that I took was to reuse the current validation logic as much as possible.

**Additional Information**
There was a discussion with product as to whether validation should be added for onblur events.
This can be found in this ticket: [PTR-94](https://issues.liferay.com/browse/PTR-94)

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
hi @ericyanLr,

It looks like you may need to rebase this pull request as there was a change upstream to view.jsp.

**Comment by ericyanLr** [comment]
Rebased this pull request: https://github.com/SamZiemer/liferay-portal/pull/323

**Pull request closed without merging**
