### PR TITLE
LPS-69984 Non-admin Permission Error for liferay-ddm:html tag

### PR DESCRIPTION
**Pull request by SGM3**
Fixes the issue where a non-admin user is unable to select content for certain elements covered in LPS-69984

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Hey @SGM3,

Using the steps provided I am still able to reproduce the issue with your fix.

**Comment by SGM3** [comment]
Hey Sam, visually looking at the change I made, what do think of them?

I'm quite sure that the solution technically works, but I'm not sure if it is the best solution.

There seems to be generated authentication tokens for the modal windows specifically. I personally do not see why we would want specific tokens for the pop-up modal windows.

Regardless, should we instead look into adding logic where the generated token also succeeds the validation logic?

**Comment by SGM3** [comment]
@SamZiemer I had to clean my cache and restart the server, a hot deploy did not work for me.

**Comment by SGM3** [comment]
@SamZiemer I was able to test it again locally, I had initially verified on linux VM, now was able to verify on my local windows.

**Comment by SGM3** [comment]
@SamZiemer NVM, it seems to be a Chrome cache that gives me a false positive.

**Comment by SamZiemer** [comment]
Closing per our skype conversation, the solution needs to be examined further.

**Pull request closed without merging**
