### PR TITLE
LPS-133675 Include javascript property when updating layout set settings properties

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-133675

The issue here was that the JavaScript in a site template was not being propagated to the sites.
To fix this, I added the javascript property to the default array in updateLayoutSetSettingsProperties method.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:reevaluate:1257401_727

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded here: https://github.com/liferay-echo/liferay-portal/pull/4799

**Pull request closed without merging**
