### PR TITLE
LPS-112114

### PR DESCRIPTION
**Pull request by brianikim**
See https://issues.liferay.com/browse/LPP-35817 for reproduction steps.

https://issues.liferay.com/browse/LPS-112114

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:stable

**Comment by brianikim** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
@brianikim This does not compile, please fix and resubmit

**Pull request closed without merging**
