### PR TITLE
LPS-69293

### PR DESCRIPTION
**Pull request by NolanChan**
Other Users can now see Locked Icon for checked-out DM files

Code originally used `hasLock` which determined whether the logged-in user had the lock. Instead switching to `isCheckedOut` as this returns whether the file is checked out regardless of user

### CODE REVIEW

**Comment by NolanChan** [comment]
I'll be updating the version and resubmitting the PR

**Comment by NolanChan** [comment]
Actually I don't understand why the versioning error went off now that I think about it... retesting

**Comment by NolanChan** [comment]
ci:retest

**Comment by NolanChan** [comment]
ci:reopen

**Comment by NolanChan** [comment]
ci:retest

**Comment by SamZiemer** [comment]
forwarded to https://github.com/dustinryerson/liferay-portal/pull/86

**Pull request closed without merging**
