### PR TITLE
LPS-73381 obscure LDAP securityCredential

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPP-26142
https://issues.liferay.com/browse/LPS-73381

The subrepo dependency has been committed to Master.  We change the System Settings configuration type to Password to obscure its values.

### CODE REVIEW

**Comment by SamZiemer** [comment]
@SpencerWoo, please update the semantic versioning. Once you do you should be able to update this pull request with a new commit and reopen.

**Comment by SpencerWoo** [comment]
ci:retest

**Comment by SpencerWoo** [comment]
ci:retest

**Comment by SpencerWoo** [comment]
It passed when I pulled myself at https://github.com/SpencerWoo/liferay-portal/pull/9#issuecomment-318517525, so assigned the LPS and LPP back to you.  Hoping it passes with this retest.

**Comment by lipusz** [comment]
Hi Guys,

Please make sure you forward this to @topolik or someone else from the Application Security team.

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1389

**Pull request closed without merging**
