### PR TITLE
LPS-120146 It should be the version 1.0.0 since we never published it

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@achaparro  in short, I can't merge this because the logic "this blocks a new app" doesn't make sense because we've added a lot of new apps this past year, and none have had this issue.

Please find a way to send this to me - passing CI.

@jpince fyi

**Pull request closed without merging**
