### PR TITLE
LPS-70168

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
> Exception in thread "main" java.lang.Exception: Missing @Override: ./modules/util/portal-tools-soy-builder/src/test/java/com/liferay/portal/tools/soy/builder/ant/ReplaceTranslationTaskTest.java 39

I didn't modify that file. Also, I ran ant-format-source-current branch before submitting, and it didn't make any changes.

**Comment by mbowerman** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/46251

**Comment by mbowerman** [comment]
These OrganizationIndexerTest failures are all happening in BChan's latest pull requests;

https://github.com/brianchandotcom/liferay-portal/pull/46256
https://github.com/brianchandotcom/liferay-portal/pull/46255
https://github.com/brianchandotcom/liferay-portal/pull/46254

etc.

**Comment by mbowerman** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Thanks for checking on those failures @mbowerman, reviewing now.

**Comment by SamZiemer** [comment]
Hey @mbowerman, I don't think this should be put into the verify process. With DXP and beyond we have changed how we do verify processes in that we no longer want to modify data while verifying.

We should instead add this as part of the document library upgrade.

If the customer does not want to run the upgrade again, we can additionally do a [post-upgrade-fix](https://github.com/liferay/liferay-portal-ee/tree/ee-7.0.x/modules/private/post-upgrade-fix) to allow the changes required to be made. Let me know if you have any questions.

**Pull request closed without merging**
