### PR TITLE
LPS-71624

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @SamZiemer,

The third commit isn't necessary for my fix because I made it call the other getSqlType method, but I thought it was probably better if we return VARCHAR rather than null for the getSqlType(String type) method if "String" is passed in. If you think it should return null instead, then feel free to remove the commit.

I did not do any versioning stuff, since my understanding is that Brian Chan is supposed to take care of that when the ServiceBuilder changes get merged in.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
hey @mbowerman the steps you have listed on the LPS are not totally clear. 
"Download the attached blade-servicebuilder.zip file and unzip it into a modules SDK."
when unzipping to liferay-portal/modules/sdk/ the buildService process errors out with a dependency issue. What location did you unzip to?

**Comment by mbowerman** [comment]
@SamZiemer I had it in the liferay-blade-samples/liferay-gradle folder (forked from https://github.com/liferay/liferay-blade-samples), but I would assume it should work in any folder that you could run `gradlew buildService` on. It's a bit annoying to test though, because until the fix gets committed and Brian Chan uploads the modified ServiceBuilder to the cdn repository, you have to install the modified ServiceBuilder into your local cache, and modify several build.gradle files to make sure everything points to the modified ServiceBuilder in your local cache instead of the latest version of the ServiceBuilder in the cdn.

**Comment by SamZiemer** [comment]
Ah ok, thanks for the info on that.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1282

**Pull request closed without merging**
