### PR TITLE
LPS-74631

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @SamZiemer,

The reason that I am doing the verify process by companyId is because it should be much faster, as it takes advantage of an existing index on (ownerId, ownerType). Not sure why we didn't have the index on (ownerType, ownerId) instead, as it seems like the ownerId is meaningless without the ownerType.

### CODE REVIEW

**Comment by mbowerman** [comment]
Fixed the rebase error and force-pushed the changes

**Comment by mbowerman** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/1415

**Comment by SamZiemer** [comment]
ci:stop

**Pull request closed without merging**
