### PR TITLE
LPS-123151 SF rule to avoid mistakes with alter column during the upgrade

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://issues.liferay.com/browse/LPS-123151>

__Notes:__
This SF rule does the following:

* Ensure that the column field names match the ones in the corresponding upgrade table class, if the class exists.
 * Only use the following data types: `BLOB`, `SBLOB`, `BOOLEAN`, `DATE`, `DOUBLE`, `INTEGER`, `LONG`, `STRING`, `TEXT`, `VARCHAR` (see [`BaseDB.java`](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/dao/db/BaseDB.java#L845-L849)).
 * When using string data types (`VARCHAR`, `STRING`, `TEXT`), we must specify whether they are nullable or not by appending `null` or `not null`.

One thing to note is that the SF rule uses the upgrade table class, __NOT__ the module's `service.xml`, to verify column names. @achaparro and I had a discussion about using the `service.xml` to verify the column names rather using the table upgrade class, since table upgrade classes will no longer be needed in the future ([LPS-134196](https://issues.liferay.com/browse/LPS-134196)). However, using only the module's `service.xml` can be problematic as column fields are removed from `service.xml` from time to time. So when we apply SF to the older upgrade processes that use column names that no longer exist in `service.xml`, false SF errors can be generated.

Let me know your thoughts. Also, we could technically both the upgrade table class and the `service.xml` to verify column names. I have an implementation for it, though the logic is a bit complicated, which is why I'm sending this version instead first.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hi @kevhlee please address the SF issue here.

**Comment by kevhlee** [comment]
Hey @SamZiemer,

Typically, SF tests fail if SF changes are being made. I can address the first two SF issues. However, I cannot resolve the third one with the `JSPStylingCheck.java` because the error was introduced after the ones in the pull request (if that makes sense). Unless I try to rebase the my changes to master.

**Comment by kevhlee** [comment]
Since I've already updated the branch, I'll go ahead the rebase the changes to current master.

**Comment by kevhlee** [comment]
Closing this pull request to create a cleaner one.

**Comment by kevhlee** [comment]
See https://github.com/SamZiemer/liferay-portal/pull/823.

**Pull request closed without merging**
