### PR TITLE
LPS-96987

### PR DESCRIPTION
**Pull request by matthewchan123**
https://issues.liferay.com/browse/LPS-96987

Reworked the fix as per our discussion in https://github.com/SamZiemer/liferay-portal/pull/609

I have deployed and executed the upgrade process on mysql after these changes, so it is confirmed not to contain syntax errors.

### CODE REVIEW

**Comment by matthewchan123** [comment]
ci:test:relevant

**Comment by matthewchan123** [comment]
ci:test:relevant

**Comment by matthewchan123** [comment]
ci:stop

**Comment by matthewchan123** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/achaparro/liferay-portal/pull/325

**Pull request closed without merging**
