### PR TITLE
Diana lin lps 85915 master 1003

### PR DESCRIPTION
**Pull request by joshuacords**
LPS: https://issues.liferay.com/browse/LPS-85915

Went through the tests and they look good.

Notes from @diana-lin 

> Problem:  Required fields which have been skipped from Form Rules remain marked as required when they are imported.  This causes a `RequiredValue` exception to be thrown.
> 
> Context:  On Form submission, required fields which have been skipped have their `required` property updated to `false`.  This same update should be imposed on Form import.
> 
> Solution:  Update Form fields to required/not required on import.  Since the functionality of `AddFormInstanceRecordMVCCommandHelper.updateRequiredFieldsAccordingToVisibility(...)` will be used in both the `dynamic-data-mapping-form-web` and `dynamic-data-mapping-service` modules, we propose creating a service.

### CODE REVIEW

**Comment by joshuacords** [comment]
See https://github.com/joshuacords/liferay-portal/pull/30#issuecomment-427426877 for test results.

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/rafaprax/liferay-portal/pull/890

**Pull request closed without merging**
