### PR TITLE
LPP-23357

### PR DESCRIPTION
**Pull request by eric-chi**
Hey Sam,

I added a quick little fix for a back button within the "My Sites" portlet. Let me know if there is any issues or any concerns.

Thanks!

### CODE REVIEW

**Comment by eric-chi** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
Hi @eric-chi,

Is there an LPS ticket associated with this? If not, you will need to make an LPS ticket, link that ticket to the LPP, and alter the commit message to show the LPS ticket number in the commit message rather than the LPP ticket number.

**Comment by eric-chi** [comment]
Hi @SamZiemer,

My mistake. I will close this and resend another one under a LPS ticket.

Again, I apologize for the mistake.

**Comment by SamZiemer** [comment]
No worries, I'll review the new one today.

**Pull request closed without merging**
