### PR TITLE
[TS] LPS-96987

### PR DESCRIPTION
**Pull request by brianikim**
Hello @SamZiemer,

Notes from @matthewchan123:

> https://issues.liferay.com/browse/LPS-96987
> 
> Issue:
> After upgrading to 7.2, the dropdown menu of child pages no longer shows when hovering a page in Site Navigation portlet.
> 
> Cause:
> ParentPlid is a column introduced to layouts in liferay 7.2, and logic has not yet been implemented to populate parentPlids of old layouts. Pages created after the upgrade have this column filled properly.
> 
> Fix:
> We can write a class that extends UpgradeProcess in Layout which gets the parent layout's plid in a SQL query and then updates the Layout table. After deploying this change, liferay should upgrade the osgi bundle, which fills the table for affected entities and correctly shows the hierarchy in the user interface.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
This upgrade process is wrong, since `layoutId` isn't unique across the whole table; it's only unique given a `groupId` and `privateLayout` value (in essence, a `LayoutSet`).

https://github.com/liferay/liferay-portal/blob/7.2.0-ga1/portal-impl/src/com/liferay/portal/service.xml#L683-L687

Additionally, since it's a table like Layout (which can have millions of rows), you should avoid one-row-at-a-time updates whenever you can, because it'll be inefficient compared to letting the database update everything in one query, which is what databases are optimized to do.

When talking with @SamZiemer, as a first guess, we had thought to use a query like this:

```sql
update Layout set parentPlid = (
	select plid
	from Layout parent
	where child.groupId = parent.groupId and
		child.privateLayout = parent.privateLayout and
		child.parentLayoutId = parent.layoutId
);
```

However, you can't perform a join against the table you are updating as part of the set clause in MySQL, so that query won't work across all databases.

This is a temporary table variation of the above, which I'm pretty sure works across databases:

```sql
create table TEMP (
	select l1.plid as plid, l2.plid as parentPlid
	from Layout l1 left join Layout l2 on
		l1.groupId = l2.groupId and
		l1.privateLayout = l2.privateLayout and
		l1.parentLayoutId = l2.layoutId
);
create unique index IX_TEMP on TEMP (plid);
update Layout set parentPlid = (
	select parentPlid
	from TEMP
	where Layout.plid = TEMP.plid
);
drop table TEMP;
```

Based on this [Stackoverflow article](https://dba.stackexchange.com/questions/41261/update-table-based-on-the-same-table), you can write a single-query MySQL version, but I don't know if it makes sense on other databases, since you aren't updating the table you specify first:

```sql
update (
	Layout l1 left join Layout l2 on
		l1.groupId = l2.groupId and
		l1.privateLayout = l2.privateLayout and
		l1.parentLayoutId = l2.layoutId
)
set l1.parentPlid = l2.plid
```

I think upgrade processes have some special class that lets you specify a query you use on all databases, and then an alternate query for specific databases (like MySQL), so that might apply here. Not sure whether the temp table route or the multi-database single query route makes more sense.

**Comment by brianikim** [comment]
Hello @matthewchan123,

Please take a look at @holatuwol 's comment here to see how to progress further for this issue. I would definitely recommend you talk to @SamZiemer in regards to how to properly implement Minchau's request here.

Sincerely,
Brian KIm

**Comment by matthewchan123** [comment]
Thanks @holatuwol  and @SamZiemer for reviewing this, I'll continue to look into and rework a solution that fits the above notes.

**Comment by SamZiemer** [comment]
After discussing this issue with Matt, he will be resending a pull to me. Closing this one for now.

**Pull request closed without merging**
