### PR TITLE
LPS-94690 Async status monitoring for remote staging

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-94690

The issue is when the site is staging. At every page load of the Control Panel, the local server would send a request to the remote server. This can cause the site to hang because the request is sent in GroupServiceHttp.getGroupDisplayURL. The timeout can take 30 seconds. Issue can also be seen on page view with the button "Go to Remote Live". 

The fix involves an ajax call for fetching the URL after everything else is loaded and rendered. But while everything is rendering, the Control Panel will contain a spinner until everything is completely loaded. Whereas the button will also be loaded after page view load. 

Within the ajax call, it would check for a remote connection and return the live URL. If the remote connection is severed, I would add its respective SessionError. Upon connection failure, it would enter failureCallback. This function displays the tooltip error. If there is no remote connection (i.e. Staging Configuration is set to Local Live) and you're on the live page, the session error would be empty and the element link would be null so it would apply the appropriate attributes.

This fix won't affect the general performance because the ajax call is done after everything else is rendered.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/moltam89/liferay-portal/pull/552

**Pull request closed without merging**
